### ISSUE TITLE
Vagrant install fails (flask.service error)

### ISSUE THREAD

**Issue by soeremk** [oracle/oci-designer-toolkit#10]
I am trying to install OCI-desiger-toolkit usign vagrant on a Windows 10 laptop with Virtual box. 
the machine creates and all looks fine until the "flask service" starts:
okit-vagrant: ‘/tmp/flask.service’ -> ‘/etc/systemd/system/flask.service’
    okit-vagrant: Created symlink from /etc/systemd/system/multi-user.target.wants/flask.service to /etc/systemd/system/flask.service.
    okit-vagrant: Job for flask.service failed because a timeout was exceeded. See "systemctl status flask.service" and "journalctl -xe" for details.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. 

systemctl status flask.service:
[vagrant@okit-vagrant ~]$ systemctl status flask.service
● flask.service - Flask daemon
   Loaded: loaded (/etc/systemd/system/flask.service; enabled; vendor preset: disabled)
   Active: activating (start) since Fri 2020-05-15 08:30:31 UTC; 1min 10s ago
 Main PID: 13894 (python3)
   CGroup: /system.slice/flask.service
           ├─13894 /usr/bin/python3 -m flask run --host=0.0.0.0 --port=8080 --no-debugger
           └─13897 /usr/bin/python3 -m flask run --host=0.0.0.0 --port=8080 --no-debugger

May 15 08:30:31 okit-vagrant systemd[1]: Starting Flask daemon...
May 15 08:30:32 okit-vagrant python3[13894]: * Serving Flask app "okitweb" (lazy loading)
May 15 08:30:32 okit-vagrant python3[13894]: * Environment: production
May 15 08:30:32 okit-vagrant python3[13894]: WARNING: This is a development server. Do not use it in a productio...ment.
May 15 08:30:32 okit-vagrant python3[13894]: Use a production WSGI server instead.
May 15 08:30:32 okit-vagrant python3[13894]: * Debug mode: on
May 15 08:30:32 okit-vagrant python3[13894]: * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
May 15 08:30:32 okit-vagrant python3[13894]: * Restarting with stat
Hint: Some lines were ellipsized, use -l to show in full.

If I try to stop the service with the vagrant user I get this error:
[vagrant@okit-vagrant ~]$ systemctl stop flask.service
Failed to stop flask.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status flask.service' for details.

I am stuck I do not know how to resolve this.
I have attached the entire install log if it is needed.
[error.txt](https://github.com/oracle/oci-designer-toolkit/files/4633197/error.txt)
I hope this can get resolved 
Thanks 
Mads

**Comment by soeremk** [comment]
I seem to have fixed it. 
In file flasl.service I changed parameter "Type=notify" to "Type=simple" then it starts. But I can not reach local host from my computer, so it might not work in the right way

**Comment by toxophilist** [comment]
@soeremk It can sometime take a short while for the Vagrant server to start responding

**Comment by toxophilist** [comment]
I'll modify the Type for future releases.

**Comment by daniel-pro** [comment]
I had the same issue as above.
I noticed in the /var/log/messages of the VM some memory errors when the startup of the flask service was invoked:
python3: page allocation failure: order:4, mode:0x14040c0(GFP_KERNEL|__GFP_COMP), nodemask=(null)

I therefore 

changed the Vagrantfile (line 27)
from 

> v.memory =384

to 

> v.memory = 1024

destroyed the VM:

> vagrant destroy

and successfully redeployed it after changing the flask.service file as described above:

> vagrant up 


I will make a PR with all the changes.

**Comment by toxophilist** [comment]
Files updated as part of other work.
