### ISSUE TITLE
Service Gateway related route rules do not allow setting a Destination Service

### ISSUE THREAD

**Issue by markmundy** [oracle/oci-designer-toolkit#109]
Service Gateway related route rules do not allow setting a Destination Service.
It is possible to select a specific destination service within a route rule relating to a service gateway. It is currently not possible to do this in OKIT and therefore not able to be provisioned or queried. This results in incorrect deployments which can lead to fails.

**Comment by toxophilist** [comment]
When Service Gateway selected the route table generates the service cidr based on the service gateway service name.
