### ISSUE TITLE
ENH REQ: Need ability to rearrange icons from query output

### ISSUE THREAD

**Issue by revnav** [oracle/oci-designer-toolkit#112]
requesting ability to rearrange the icons displayed when querying a tenancy. For example I have about 10-15 compute instances running in compartment and querying the compartment gives me display which has compute instances stack horizontal. It is really difficult to view or present the output... see sample below

![image](https://user-images.githubusercontent.com/8673231/93962511-d3532600-fd0f-11ea-8892-c1894002166e.png)

**Comment by toxophilist** [comment]
Added to OCD [Release](https://github.com/oracle/oci-designer-toolkit/releases)
