### ISSUE TITLE
ERROR: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by devopyes** [oracle/oci-designer-toolkit#113]
Not able to generate terraform code while having autonomous data warehouse services exists in the layout. 

okit    | ERROR: object of type 'NoneType' has no len()
okit    | Traceback (most recent call last):
okit    |   File "/okit/okitweb/okitWebDesigner.py", line 227, in generate
okit    |     generator.generate()
okit    |   File "/okit/visualiser/generators/okitGenerator.py", line 188, in generate
okit    |     self.renderAutonomousDatabase(autonomous_database)
okit    |   File "/okit/visualiser/generators/okitGenerator.py", line 236, in renderAutonomousDatabase
okit    |     if len(autonomous_database['whitelisted_ips']):
okit    | TypeError: object of type 'NoneType' has no len()

**Comment by toxophilist** [comment]
@devopyes which version are you using because the whitelisted_ips should never be None.

**Comment by devopyes** [comment]
Version 0.11.0

**Comment by toxophilist** [comment]
Fixed in next release
