### ISSUE TITLE
ENH REQ: Have an export option to export to Git for integration with Resource Manager

### ISSUE THREAD

**Issue by markmundy** [oracle/oci-designer-toolkit#115]
This might be an odd one but some users would like to be able to export to a Git respository and then have RM build a stack from there. Currently it is not possible without configuration changes to have exported tf be pushed to a git repository and then have Oracle Resource manager utilise it.

Might be nice to allow this to happen especially as this is what is done when okit exports directly to RM.

**Comment by toxophilist** [comment]
Fixed in 0.12.0 release
