### ISSUE TITLE
ENH REQ: Need ability to wrap oci resources across the entire canvas

### ISSUE THREAD

**Issue by markmundy** [oracle/oci-designer-toolkit#122]
Currently when OCI is drawn using OKIT, elements such as subnets are dropped on the the canvass and appear in a vertical line under each other. This leaves a lot of whitespace on the canvas that is not used and so after exporting to an image for use in things such as presentations it is hard to show correctly.

Would it be possible to wrap resources around the canvass in a way more appropriate for showing?

**Comment by jdavies** [comment]
Or (best wish list item) be able to manually drag and drop the subnects and all of their contents manually so the user can place them more logically.

**Comment by jngithub1** [comment]
Yes indeed, this would be a great improvement
