### ISSUE TITLE
Enhancement Request: Provide preference for or dynamic toggle to display labels on artifacts.

### ISSUE THREAD

**Issue by chrisfw** [oracle/oci-designer-toolkit#126]
Hi, 
First off, I'd like to thank you for creating this very useful tool!
I wanted to note that It would be very helpful to control the display of labels on different artifacts, e.g. block storage volumes either through a global preference or dynamic context selection.  Currently, for example, the block storage volume name only displays when hovering over the element.  Due to layout screen real estate and containing element constraints, it would be great if the font size were configurable as well.  

Regards,
Chris Whelan

**Comment by toxophilist** [comment]
New preferences added for displaying labels on all artefacts in v0.14.0 release

**Comment by chrisfw** [comment]
This is great news  - thank you Andrew!
Regards,
Chris
