### ISSUE TITLE
Issue with visualization of block volumes

### ISSUE THREAD

**Issue by chrisfw** [oracle/oci-designer-toolkit#131]
Hello, 

There appears to be an issue with the rendering of block volumes attached to an instance under certain conditions.  The only difference I can see between those compartments that work and the one that does not in our tenancy is that the block volume attachments in this compartment are iscsi, but that doesn't seem like it should impact rendering

This is in reference to Version 0.12.0.  When I navigate to the incorrectly rendered instance in the OCI portal, there are 5 attached volumes.  You can see from the size of the bounding rectangle surrounding the instance in the image that space has been reserved for rendering the 5 volumes and one rectangle is created for the first volume, but they are not actually inserted.  I am not sure of how best to assist in resolving this issue.  Please advise if you would like additional information.

![atl-bv-issue](https://user-images.githubusercontent.com/6135741/95579877-6379b680-0a04-11eb-81ef-b16c9bd09429.png)

**Comment by toxophilist** [comment]
@chrisfw If you open the browser Developer tool console do you see any errors

**Comment by chrisfw** [comment]
@toxophilist , no, apparently there are no errors according to the console.

![image](https://user-images.githubusercontent.com/6135741/95654640-4fe75200-0acf-11eb-964f-c271d1ccaf82.png)

**Comment by toxophilist** [comment]
@chrisfw I'll see if I can reproduce this next week.

**Comment by chrisfw** [comment]
Thanks @toxophilist, much appreciated!

Regards,
Chris

**Comment by toxophilist** [comment]
@chrisfw oddly when I create / deploy / query the block volumes appear correctly, although I do tend to clear my cache / hard reload regularly. I'll keep investigation but will be revisiting the drawing functionality for Issue #126 so may resolve it as part of that work.

**Comment by chrisfw** [comment]
Thanks Andrew.  That is strange.  I wish I could give you read only access to the compartment so you could easily reproduce it, but that would require a NDA and I'd have to obtain customer permission, etc., etc.  If I can reproduce it in a separate dev tenancy, I will let you know.  Please let me know if there is anything else I can do to assist.
Regards,
Chris

**Comment by toxophilist** [comment]
@chrisfw Do the Block Volumes exist in a compartment that has not been queried. I can repro this if I define my block storage in a separate compartment from the instance and only query the compartment with the instance in it. I'll have to think how to resolve this issue.

**Comment by chrisfw** [comment]
@toxophilist , no the block volumes exist in the same compartment as the instance, vcn, etc. I am querying directly from the tool.
Thanks,
Chris

**Comment by toxophilist** [comment]
@chrisfw Thanks I'll keep looking

**Comment by toxophilist** [comment]
Unable to reproduce
