### ISSUE TITLE
Export to terraform failing (sometimes)

### ISSUE THREAD

**Issue by scanlonjts** [oracle/oci-designer-toolkit#144]
I can query and export to terraform for a few different profiles but have one that fails. 
i run from docker

logs: docker logs okit --follow

ERROR: 'ocid1.subnet.oc1.iad.xxxxxx'
Traceback (most recent call last):
  File "/okit/okitweb/okitWebDesigner.py", line 230, in generate
    generator.generate()
  File "/okit/visualiser/generators/okitGenerator.py", line 206, in generate
    self.renderInstance(instance)
  File "/okit/visualiser/generators/okitGenerator.py", line 610, in renderInstance
    self.jinja2_variables["subnet_id"] = self.formatJinja2IdReference(self.standardiseResourceName(self.id_name_map[instance["vnics"][0]["subnet_id"]]))
KeyError: 'ocid1.subnet.oc1.iad.xxxxxx'

**Comment by scanlonjts** [comment]
![image](https://user-images.githubusercontent.com/4170845/96282934-61d26480-0fa9-11eb-9adf-01410e2d32ca.png)

**Comment by toxophilist** [comment]
@scanlonjts I suspect that is because the subnet is missing from the design.
