### ISSUE TITLE
Query only show limited number of machines

### ISSUE THREAD

**Issue by xperiazn** [oracle/oci-designer-toolkit#148]
I have around 20 VM, 6 DBCS and 2 ATP databases.
Query only shows couple of VM-s.
All vm-s are shown in explorer but not drawn on screen.
Any idea how to repair that?

**Comment by toxophilist** [comment]
@xperiazn Are they part of OKE cluster

**Comment by xperiazn** [comment]
Some are and some are not.
30 instances in total. 8 of them are from kubernetes cluster.

![image](https://user-images.githubusercontent.com/44767327/97004106-ce66d980-153c-11eb-90ca-fb4f0e27322e.png)


![image](https://user-images.githubusercontent.com/44767327/97004053-ba22dc80-153c-11eb-83a7-831d7e41e04f.png)

**Comment by toxophilist** [comment]
@xperiazn the ones associated with one will not be displayed but I can see that it has calculated the space for the instances but not displayed them. I'm wondering if this is associated with #131

**Comment by toxophilist** [comment]
@xperiazn can you attach the json associated with this diagram.

**Comment by xperiazn** [comment]
@toxophilist can you please explain how to attach the jason?

**Comment by xperiazn** [comment]
same behavior under 0.13.0

**Comment by toxophilist** [comment]
@xperiazn You should be able to drag it onto the comment box to upload

**Comment by toxophilist** [comment]
If this is still occuting please reopen with example json
