### ISSUE TITLE
ENH REQ: Need to show a short description on mouse-over

### ISSUE THREAD

**Issue by jdavies** [oracle/oci-designer-toolkit#149]
Great work on this BTW. I'm using v0.12.0. Right now the Display Name field (specifically for an instance) is what is displayed on the screen. However, I'd like to also have the option of using either a short description, or adding a "machine name" field. My reasoning is this: The machine name is hat should be used when defining the machine in Terraform/Ansible. However, when I'm showing the design to others, I would prefer that the display name be the name that we more commonly use.

For example, I have a JDA deployment with 2 file servers. Their machine names are CATMANJDAFS1 and CATMANJDAFS2. I would like to associate a common name with each one (CatMan File Server 1 and CatMan File Server 2 respectively) so that the managers/directors and the odd C-Level exec don't have to know the IT naming standards. When mousing over the compute instance icon, a tool tip with the machine name should popup, but it's the common name that I normally want to see n the diagram.

**Comment by toxophilist** [comment]
@jdavies I'm currently doing some work in this area with respect to display information for canvas artefacts allowing the user to display name / type / additional information (probably description). In addition I'll be looking at the mouse over pop up to display summary information. This is all part of some on going visual clean up and modification to automatic layout.

**Comment by toxophilist** [comment]
Definition field implemented for all artefacts in v0.14.0 in addition the user has the ability to change display labels & mouse over information
