### ISSUE TITLE
OCI_CONFIG_DIR point to wrong directory

### ISSUE THREAD

**Issue by fuadar** [oracle/oci-designer-toolkit#15]
in the Doc for 0.50
export OCI_CONFIG_DIR=~/.oci/oci.config . This failed because docker is trying to mount this as a directory it needs to be 
export OCI_CONFIG_DIR=~/.oci

**Comment by toxophilist** [comment]
The environment variable is for you to specify the directory where you have your config located and the docs show an example. The 5.1 release does not specifically use this because the docs show the full example docker command.
