### ISSUE TITLE
Display Grid checkbox requires a manual page refresh

### ISSUE THREAD

**Issue by JeromeFr** [oracle/oci-designer-toolkit#158]
Thanks for this great tool!

Small GUI issue : the grid doesn't disappear when I unselect the Display Grid checkbox in the Preferences.

Okit version: 0.12.0
Chrome Version 86.0.4240.75 (Official Build) (64-bit) on Windows 10.
![image](https://user-images.githubusercontent.com/3862497/97368949-3bb39b00-18ac-11eb-9e03-b0d4439773a9.png)

**Comment by toxophilist** [comment]
@JeromeFr this is usually resolved when you refresh the browser of select new.

**Comment by JeromeFr** [comment]
That's right, thanks for the workaround.
So the new issue description is : If I toggle the Display Grid checkbox (regardless its current state), nothing happens unless I manually refresh the page.

**Comment by toxophilist** [comment]
Will be fixed in 0.14.0
