### ISSUE TITLE
Cost Estimator fails to estimate dbaas included.

### ISSUE THREAD

**Issue by markmundy** [oracle/oci-designer-toolkit#163]
The following error is thrown when dbaas is included.

File "/okit/visualiser/model/okit_price_v2.py", line 228, in price_calculator
    dbaas_storage += dbaas['data_storage_size_in_gb'] + 456
TypeError: must be str, not int

**Comment by toxophilist** [comment]
Need to wrap dbaas['data_storage_size_in_gb'] in specific int conversion
