### ISSUE TITLE
Load Balancers should not stack vertically in a subnet

### ISSUE THREAD

**Issue by jdavies** [oracle/oci-designer-toolkit#166]
As of v0.13.0 if I put a load balancer and a compute instance in a subnet, the LB will always be placed on top of the computer instance. I usually adda LB to a public subnet and have it balance over compute instances in a private subnet, so placing the LB at the top in a subnet would only make sense in those instances where it was balancing over instances with the subnet that contains it.

Perhaps the placement of the LB could be more contextual? Placing it at the top or bottom if a subnet depending on the subnet of the instances over which it is balancing?

**Comment by toxophilist** [comment]
Resolve in new OCD release https://github.com/oracle/oci-designer-toolkit/releases
