### ISSUE TITLE
ENH REQ: OKIT needs to have an autosave capability.

### ISSUE THREAD

**Issue by markmundy** [oracle/oci-designer-toolkit#169]
Too many times do you draw something and then accidentally close your browser before saving and everything is lost. OKIT needs the ability to automatically save work to a default downloads directory or have some way of reducing stress caused by losing work.

**Comment by toxophilist** [comment]
@markmundy We can periodically execute the save but this will use the browsers standard save functionality it that is configured to automatically save to the downloads it would do so. If configured to ask each time then the user would be asked  if they want to save.

**Comment by scross01** [comment]
How about using HTML5 Web Storage `window.localStorage` to persist data in the browser automatically

**Comment by toxophilist** [comment]
Released in version 0.14.0
