### ISSUE TITLE
On resource manager bool values with a capital letter (True/False) fail the job (on Firefox 68.7.0esr (64-bit) OSX)

### ISSUE THREAD

**Issue by mikarinneoracle** [oracle/oci-designer-toolkit#18]
When I fixed bool values manually by editing the job in Resource Manager stack and changing values true/false instead of True/False the job would work without errors.

**Comment by mikarinneoracle** [comment]
<img width="666" alt="Screenshot 2020-05-19 at 19 50 48" src="https://user-images.githubusercontent.com/22078405/82360247-c47efe80-9a11-11ea-8a6d-b4b5eb412e21.png">

**Comment by toxophilist** [comment]
@mikarinneoracle This will be resolved in the v0.6.0 release where the variable will not be used for RM. Variables are being removed to get around the 100 variable limit in RM.

**Comment by mikarinneoracle** [comment]
thank you!
