### ISSUE TITLE
Unable to install on Linux systems

### ISSUE THREAD

**Issue by philstepson** [oracle/oci-designer-toolkit#180]
Attempting to build the Docker image On CentOS 8 from the script:
**_./build-docker-image.sh_**

Receiving the following error related to a yum repository:
**_https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: yum.oracle.com; Unknown error_**

The Linux host has access to the internet and I'm able to access the URL outside of the Docker image build script.

Is there support only for Linux 7 at a specific release level for the oci-designer-toolkit , or are any Linux distros supported?
I have attempted to install on Oracle Linux 7.8 with the same issue. (No issues running the script and software on macOS Catalina).

**Console output displaying the steps leading to the error:**

[pwstephe@CentOS8PWS scripts]$ ./build-docker-image.sh
Error response from daemon: Cannot kill container: okit: No such container: okit
Error: No such image: okit
*******************************************************************
**                                                               **
**  Building OL7 Image                                           **
**                                                               **
*******************************************************************
Sending build context to Docker daemon  9.186MB
Step 1/12 : FROM oraclelinux:7-slim
 ---> 2f44bb7409d2
Step 2/12 : LABEL "provider"="Oracle"       "issues"="https://github.com/oracle/oci-designer-toolkit/issues"       "version"="0.14.1"       "description"="OKIT Web Server Container."       "copyright"="Copyright (c) 2020, Oracle and/or its affiliates."
 ---> Running in bf1840f08440
Removing intermediate container bf1840f08440
 ---> d33a9e5b6875
Step 3/12 : SHELL ["/bin/bash", "-c"]
 ---> Running in 6c06e6bd4d5c
Removing intermediate container 6c06e6bd4d5c
 ---> fd84400fabdf
Step 4/12 : ENV PYTHONIOENCODING=utf8     PYTHONPATH=":/okit/visualiser:/okit/okitweb:/okit"     FLASK_APP=okitweb     FLASK_DEBUG=1     LANG=en_GB.UTF-8     LANGUAGE=en_GB:en     LC_ALL=en_GB.UTF-8     PATH=/root/bin:${PATH}
 ---> Running in dd187d4acda4
Removing intermediate container dd187d4acda4
 ---> 57f15f9448e3
Step 5/12 : EXPOSE 80
 ---> Running in ef51e7e075c4
Removing intermediate container ef51e7e075c4
 ---> bb35ba061ea3
Step 6/12 : EXPOSE 443
 ---> Running in ff31a73e7d65
Removing intermediate container ff31a73e7d65
 ---> 292ee0c70014
Step 7/12 : RUN yum install -y     oracle-softwarecollection-release-el7     oraclelinux-developer-release-el7  && yum-config-manager --disable ol7_ociyum_config  && yum update -y  && yum install -y         python36         python3-pip  && rm -rf /var/cache/yum  && python3 -m pip install --upgrade pip  && pip3 install --no-cache-dir         flask==1.1.1         gunicorn==20.0.4         oci==2.22.0         pandas==1.1.2         python-magic==0.4.18         pyyaml==5.3.1         requests==2.24.0         xlsxwriter==1.3.6  && mkdir -p /okit/{config,log,visualiser,okitweb,workspace,templates}  && mkdir -p /okit/okitweb/static/okit/templates  && ln -s /okit/templates /okit/okitweb/static/okit/templates/user
 ---> Running in 838d1e7a2f13
Loaded plugins: ovl
https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: yum.oracle.com; Unknown error"
Trying other mirror.

 One of the configured repositories failed (Oracle Linux 7Server Latest (x86_64)),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=ol7_latest ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable ol7_latest
        or
            subscription-manager repos --disable=ol7_latest

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=ol7_latest.skip_if_unavailable=true

failure: repodata/repomd.xml from ol7_latest: [Errno 256] No more mirrors to try.
https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: yum.oracle.com; Unknown error"
Removing intermediate container 838d1e7a2f13

**Comment by toxophilist** [comment]
@philstepson If you execute
```bash
docker run -it --rm oraclelinux:7-slim /bin/bash
```
Can you execute 
```bash
yum update -y
```

Also where are you trying to create the docker container.

**Comment by javierbm7** [comment]
Hi @philstepson i solved with these steps: 


# sudo cd /etc/yum.repos.d/

#sudo wget http://yum.oracle.com/public-yum-ol7.repo

#sudo nano public-yum-ol7.repo

Edit the file to enable repos ol7_UEKR4, ol7_addons  to anable flag

![image](https://user-images.githubusercontent.com/40583067/100021584-b5f21500-2daf-11eb-9cb2-d22a5f51b928.png)

![image](https://user-images.githubusercontent.com/40583067/100021591-bb4f5f80-2daf-11eb-92f4-da483ea3bd4b.png)


# firewall-cmd --zone=public --add-masquerade --permanent
# firewall-cmd --reload

"Reboot or restart dockerd, and both ingress and egress should work."
# service docker restart

**Comment by philstepson** [comment]
Excellent - Well done.
Thanks!
Phil

**Comment by toxophilist** [comment]
@philstepson @javierbm7 Are you running OL7 / Centos locally on your laptop

**Comment by javierbm7** [comment]
> 
> 
> @philstepson @javierbm7 Are you running OL7 / Centos locally on your laptop

Hi @toxophilist, in my case running in OCI compute instance with OL8

**Comment by toxophilist** [comment]
@javierbm7 There are separate instructions for OCI Compute Instance installation that do not use Docker. Also yum issues associated with OCI installation tend to be resolved following these [Connecting To Yum Mirrors in Oracle Cloud Infrastructure (OCI)](instructions https://yum.oracle.com/getting-started.html#connecting-to-yum-mirrors-in-oracle-cloud-infrastructure-oci).

I have also seen some comments that the default, yum based, docker install on OL is not the latest and needs updating manually.
