### ISSUE TITLE
Adding an instance and an autonomous database in the same compartment overlays them on the canvas

### ISSUE THREAD

**Issue by markmundy** [oracle/oci-designer-toolkit#187]
If you create a compartment in OKIT and try to drop a compute instance and an autonomous database in to it, the 2 icons representing them get drawn over the top of each other making it impossible to configure the properties of the one underneath and to display properly.
This works fine if you place them on a subnet within the compartment, it is only when you are trying to represent a situation where the subnet they reside on is in a different compartment.

[displaycompartmentbug.json.zip](https://github.com/oracle/oci-designer-toolkit/files/5602886/displaycompartmentbug.json.zip)

**Comment by toxophilist** [comment]
Fixed in 0.15.0 release
