### ISSUE TITLE
Undefined variable in ansible export

### ISSUE THREAD

**Issue by duhlig** [oracle/oci-designer-toolkit#189]
* Type: Bug or PEBKAC
* OKIT version: 0.14.1
* Component: Ansible generator
* Severity: medium, workaround possible
* Description:
  * To reproduce: I "draw" a rudimentary configuration with only one VCN and the bastion fragment. Only the bastion's subnet CIDR needs to be changed. Then I export the content to Ansible.
  * Problem: In okit-ansible.zip/main.yml the task named "Create Security List okit-bastion-sl" tries to use the variable Okit_Vcn001_default_security_list_id and fails.
  * Workaround: This variable should have been set in set_fact just after "Create Virtual Cloud Network okit-vcn001" but is missing there. It can manually be added in main.yml
* Attached files:
  * [okit.json.zip](https://github.com/oracle/oci-designer-toolkit/files/5607397/okit.json.zip)
  * [okit-ansible.zip](https://github.com/oracle/oci-designer-toolkit/files/5607400/okit-ansible.zip)

**Comment by toxophilist** [comment]
Variable will be added in the 0.15.0 release.

Just as an FYI we will be upgrading to the Ansible Collection version of the in the New Year
