### ISSUE TITLE
Easier way to use it under Windows ?

### ISSUE THREAD

**Issue by cfornale** [oracle/oci-designer-toolkit#19]
I mean our Oracle Windows image that we have on our company laptops which doesn't support WSL2 so I cannot run Linux and run the docker with Linux kernel...

any simple suggestion would be very welcome... 

many thnx in advance
-Cla

**Comment by toxophilist** [comment]
@cfornale this is one of the reasons we added the Vagrant/VBox solution. We are continuing to look into docker/windows.

**Comment by toxophilist** [comment]
Version 0.7.0 will have some PowerShell scripts for building / starting docker in the containers/scripts directory
