### ISSUE TITLE
okit Docker in Win 10 Pro fails with error

### ISSUE THREAD

**Issue by mp3monster** [oracle/oci-designer-toolkit#194]
Trying to use the Docker build and run, Docker image fails reporting:

standard_init_linux.go:211: exec user process caused "no such file or directory"

This is on windows 10 with Docker for Windows installed, WSL2

**Comment by toxophilist** [comment]
@mp3monster What was the build command you were using

**Comment by mp3monster** [comment]
I followed instructions on https://github.com/oracle/oci-designer-toolkit/blob/master/documentation/Installation.md pointing to:

 docker build --tag okit --force-rm https://github.com/oracle/oci-designer-toolkit.git

docker run -d --rm -p 80:80 --volume <USER HOME DIR>/okit/user/templates:/okit/templates --volume <USER HOME DIR>/.oci:/root/.oci --name okit okit

As you'll see on my blog I did a bit of looking around, and that error is often associated with Linux/Windows line termination problem.  When I switched to running the build inside of a Linux using WSL2 all went fine.

See https://blog.mp3monster.org/2020/12/08/okit-oci-design-on-windows/

**Comment by toxophilist** [comment]
@mp3monster Hmm LF/CR issues is that in the config file within the .oci directory or the Dockerfile. 

Windows was one of the reasons we provided the Vagrant build option.

**Comment by toxophilist** [comment]
The work around for this issue can be found https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings where it will show how to configure git to resolve this.
