### ISSUE TITLE
unable tu pull

### ISSUE THREAD

**Issue by xperiazn** [oracle/oci-designer-toolkit#2]
git clone -b v0.5.0 --depth 1 git@github.com:oracle/oci-designer-toolkit.git

**Comment by xperiazn** [comment]
tkralj@LAPTOP-G2NEECGB:~$ git clone -b v0.5.0 --depth 1 git@github.com:oracle/oci-designer-toolkit.git
Cloning into 'oci-designer-toolkit'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

**Comment by mattiarossi** [comment]
or, you can use the http link to the repo that does not require authentication for pulls:
```
git clone https://github.com/oracle/oci-designer-toolkit.git
```

I think the README should mention that

**Comment by toxophilist** [comment]
Updated the Installation guide to include both clone commands.
