### ISSUE TITLE
Unable to place networking and other resources in Compartment that does not have VCN

### ISSUE THREAD

**Issue by mrich14287** [oracle/oci-designer-toolkit#202]
Our OCI design calls for putting all project specific resources in a compartment for that project while globally shared resources are stored in a general compartment.  

Some project resources such as subnet, file systems, and load balancers cannot currently be placed in a compartment that does not have a VCN in it.  Our VCNs are globally shared resources so they are not in the same compartment with the subnets or file systems.

We would however in the properties file be able to link the subnet to it's VCN.

**Comment by toxophilist** [comment]
Added to OCD [Release](https://github.com/oracle/oci-designer-toolkit/releases)
