### ISSUE TITLE
Unable to save as template 

### ISSUE THREAD

**Issue by mantechexperts** [oracle/oci-designer-toolkit#204]
I tried queirying the my existing environment and i am success and got the details of resource. When i try to save as template , i am unable to select ( When i try to choose/select option ) it is allowing to me to select

Kindly advice

**Comment by toxophilist** [comment]
@mantechexperts  Can you open the Developer tools in your browser and check the console log to see it there any errors

**Comment by toxophilist** [comment]
@mantechexperts are you still seeing this issue

**Comment by toxophilist** [comment]
Closed due to no response
