### ISSUE TITLE
Queries fail to retrieve Object Storage Bucket names

### ISSUE THREAD

**Issue by simonpane** [oracle/oci-designer-toolkit#206]
Queried **Object Storage Bucket** names are not retrieved and instead are displayed as `okit-osb001` etc.  These OKIT generated bucket names are shown in all three places: the Palate Explorer, the main Canvas, and the Properties window.  Other OS bucket details such as the creation date and creation user are accurate.

Example:

![image](https://user-images.githubusercontent.com/17480670/104242145-f408ce00-541b-11eb-89f0-230185b77c8a.png)

Command: `grep -i ociObjectStorageBuckets /okit/log/okit-debug.log | grep name` does indeed show the name in the DEBUG log entries JSON (not pasted here for brevity).

Possible issue (guessing) is Storage Bucket name length - all buckets in compartment are more than 22 characters in length.

Using latest version of OKIT via Docker container (downloaded from registry on Jan 11, 2021).  Specific version details:

- Version 0.15.0 (9th December 2020)

**Comment by toxophilist** [comment]
Name copied to display_name during the query in v0.16.0

**Comment by simonpane** [comment]
I'm not sure this has been resolved.  Trying on version 0.17.0 and the object storage buckets are no longer displayed at all.

Tested against multiple compartments in multiple regions - no longer see object storage buckets in either the Palette or the Explorer.
