### ISSUE TITLE
Need ability to query multiple compartments at a time

### ISSUE THREAD

**Issue by revnav** [oracle/oci-designer-toolkit#21]
We follow standard practice of keeping network and compute/storage/DB etc under separate compartments. using OKIT we can only query one compartment at a time, either NET or compute/storage/DB.
The OKIT show compute/storage/DB etc without VCNs as they are not under same  compartment. Need an ability to pick multiple compartments to draw the complete picture.

**Comment by toxophilist** [comment]
@revnav If you pick a higher level compartment it will query sub compartments to bring back that information.

**Comment by revnav** [comment]
@toxophilist Yeah, I tried that already. We cannot pick the root compartment from the query option. It only give first level compartments underneath the root.
We have NET under root and then other compartments. The only parent for all is the root level compartment.

**Comment by toxophilist** [comment]
@revnav dded Tenancy Root to the list of selectable compartment. This will be in the 0.6.0 release.
