### ISSUE TITLE
Generate not working for queried resources

### ISSUE THREAD

**Issue by revnav** [oracle/oci-designer-toolkit#22]
I am not able to generate terraform/ansible or resource manager files for the queried resources from existing tenancy. Tried two different tenancies.

I am running it as docker on mac using docker engine:19.03.8, compose:1.25.5
All three generate options give the following errors:

ERROR: invalid literal for int() with base 10: 'None'
Traceback (most recent call last):
  File "/okit/okitweb/okitWebDesigner.py", line 200, in generate
    generator.generate()
  File "/okit/visualiser/generators/ociGenerator.py", line 166, in generate
    self.renderSubnet(subnet)
  File "/okit/visualiser/generators/ociGenerator.py", line 1159, in renderSubnet
    if int(str(subnet.get("availability_domain", "0"))) > 0:
ValueError: invalid literal for int() with base 10: 'None'

**Comment by revnav** [comment]
please note that in both the tenancies the subnets were regional subnets.

**Comment by toxophilist** [comment]
@revnav will be resolved in 0.6.0 release
