### ISSUE TITLE
US Government Regions

### ISSUE THREAD

**Issue by henremurr** [oracle/oci-designer-toolkit#220]
When I try to export to Resource Manager, I don't see any US Govt Regions. I've tried making mods to my local copy of okitweb/static/okit/json/dropdown.json (as seen below) but still haven't figured out how to make it work. As a US Govt customer, I would really like to have this capability in OKIT.

    {
      "display_name": "US Ashburn",
      "id": "us-ashburn-1",
      "key": "IAD",
      "name": "us-ashburn-1"
    },
    {
      "display_name": "US Gov East",
      "id": "us-langley-1",
      "key": "LFI",
      "name": "us-langley-1"
    },
    {
      "display_name": "US Phoenix",
      "id": "us-phoenix-1",
      "key": "PHX",
      "name": "us-phoenix-1"
    },
    {
      "display_name": "US Gov West",
      "id": "us-luke-1",
      "key": "LUI",
      "name": "us-luke-1"
    },

Can this be supported in future (next) release? Or, can show me what to do.
Thanks

**Comment by toxophilist** [comment]
@henremurr I do plan on extending this so Gov regions are displayed / accessible

**Comment by henremurr** [comment]
Hi Andrew,

That’s awesome news!

I’ve successfully demonstrated OKIT capabilities in OCI commercial and was bummed when it didn’t work in OCI Government.

I’m currently leading an OCI Gov capabilities study and this new OKIT extension would really help me close the deal.

You all have created a fantastic product. I’m excited to start testing.

Regards 👍

**Comment by toxophilist** [comment]
@henremurr Is your Gov tenancy the Default in the config file. If not can you try setting it as the default and rebuild your okit container. The reason for this is that OKIT is shipped with a basic set of information for the drop downs you see within the tool but on page load it will attempt to update this information by querying the default connection. This may bring back yours gov region.

I do not have access to Gov regions so can not test this but if you could try I'd appreciate it. If you watch the browser dev tools console you will see this has completed when a message appears saying it's saved the dropdown.json file.

**Comment by henremurr** [comment]
I’ve put the config file in /okit and rebuilt — not picking up us-langley-1 defaults. I’m probably doing something wrong?? i’ll keep trying and provide you with an update tonight or tomorrow

Merci beaucoup 👨‍🎨

**Comment by henremurr** [comment]
I haven’t been able to override Default when exporting to Resource Manager. I can add a Custom and it shows up under drop down. I coded the Gov’t OCiD but popup is not seeing and Gov region. I  updated Okit to 0.17.0 but that didn’t change anything — let me know if you want me to try something else.

**Comment by henremurr** [comment]
So reaming default to custom broke oci command line. Put reverted custom to default and oci is working again. It looks like in 0.17 when I use us-langly-1 OKIT can't find a match and returns AP Chuncheon which happen to be the first in the region drop down list. In the prior version 0.16, it defaulted to US-ASHBURN? Not sure this helps.

**Comment by henremurr** [comment]
Update -- changed key file to use ~/.okit vs absolute path and rebuilt -- OKIT now connects to OCI. It loads my compartments, but the region is still not being found. It can't translate us-langley-1 to "US Gov East (Ashburn)" or us-luke-1 to "US Gov West (Phoenix)". I will try making the changes to okitweb/static/okit/json/dropdown.json (0.17.0) and rebuilding -- getting closer.

**Comment by henremurr** [comment]
vi /okit/oci-designer-toolkit/okitweb/static/okit/json/dropdown.json
added to bottom:
      "name": "us-sanjose-1"
    },
    {
      "display_name": "US Gov East",
      "id": "us-langley-1",
      "key": "LFI",
      "name": "us-langley-1"
    },
    {
      "display_name": "US Gov West",
      "id": "us-luke-1",
      "key": "LUI",
      "name": "us-luke-1"
    }
  ],

Rebuilt and it's there (albeit at the end); going to move my regions to the top of the list and rebuild (again) -- this time, I think it might actually work.

**Comment by henremurr** [comment]
My rebuild commands for those having trouble:
cd /okit/oci-designer-toolkit/containers/docker ;  docker-compose stop ; docker-compose rm ;  docker rmi okit
docker-compose up --detach ; docker-compose top

**Comment by henremurr** [comment]
Update -- Resource Manager link works nicely; albeit I haven't actually done a deployment yet. In the popup, the region defaults on load to "US Gov East" and Compartment refresh (refreshes) and shows root (/) and all the other compartments I have created. No red OCI connection icon top right. That was fixed by using a relative path vs absolute path (see comments).

Clicking on the console cloud icon top right, fails to connect -- the URL is "console.us-langley-1.oraclecloud.com" and should be "console.us-langley-1.oraclegovcloud.com" -- missing gov. I will search for the URL and see if I can fix that too.

**Comment by henremurr** [comment]
I found four additional files with oraclecloud hard-coded (didn't change them at this time).

/okit/oci-designer-toolkit/okitweb/templates/reference_architecture/sql_server.json
/okit/oci-designer-toolkit/visualiser/model/bom.py
/okit/oci-designer-toolkit/visualiser/model/calculator.py
/okit/oci-designer-toolkit/visualiser/model/okit_price_v2.py

Summary of my changes to make Resource Manager, Connection, and Console work with US Govt tenancy
1. change key file to use ~/.okit vs absolute path
2. added regions to (top) of vi /okit/oci-designer-toolkit/okitweb/static/okit/json/dropdown.json
3. changed "oci_href" in  js/okit_designer.js
4. destroyed old docker build with cd /okit/oci-designer-toolkit/containers/docker ; docker-compose stop ; docker-compose rm ; docker rmi okit
5. make a new docker build with docker-compose up --detach ; docker-compose top
