### ISSUE TITLE
OKIT-GitHub Connection

### ISSUE THREAD

**Issue by henremurr** [oracle/oci-designer-toolkit#226]
I need to connect OKIT to GitHub. I followed the instructions in the Install Guide and finally figured out how to make it work. However, it won't save files? I can load files from the repo but I have to save them as okit (n).json where n is some number, then check out the file, open the downloaded file, paste in the contents, save and push.

Have I got something wrong?

Also a Save As would be a nice feature.

Please advise.

**Comment by toxophilist** [comment]
@henremurr with the git integration the save should just do a git add/push. I'll take a look see if I can reproduce the  issue

**Comment by henremurr** [comment]
thanks
