### ISSUE TITLE
Enhancement request: Add Heatwave and Replication Channels to the MySQL DB Systems

### ISSUE THREAD

**Issue by vittoriocioe** [oracle/oci-designer-toolkit#268]
It would be extremely useful to have in the MySQL DB System Block option to add replication channel and Heatwave cluster.
Terraform already provides functions, described here:
https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/mysql_channel
https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/mysql_analytics_cluster

Thanks a lot.

P.S. If help is needed on MySQL side I am happy to help

**Comment by toxophilist** [comment]
In 0.47.0
