### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by LotToLearn** [oracle/oci-designer-toolkit#269]
Hi,

I can get OKIT up and running, no issues. 
Keys are in OCI, and it can authenticate that by listing the compartments when I go to query

But, the query always fails. The logs aren't too helpful to be honest, this is the only thing that really says anything...

DEBUG : okitWebDesigner[0450] : JSON : 
{'title': 'Query Failed', 
'description': 'Internal Server Error', 

Vague, I know -- any ideas?

**Comment by toxophilist** [comment]
@LotToLearn if you execute `docker logs okit` from the command line you should be able to see the server error alternatively you could try opening the docker desktop console.

I suspect this is because it failed to authenticate does the entry in your config for the key_file point to `~/.oci/<KEY FILE>`

**Comment by LotToLearn** [comment]
> @LotToLearn if you execute `docker logs okit` from the command line you should be able to see the server error alternatively you could try opening the docker desktop console.
> 
> I suspect this is because it failed to authenticate does the entry in your config for the key_file point to `~/.oci/<KEY FILE>`

Hey, thanks for such a fast reply. Appreciated a ton.

I have the write keys, and I made sure to ~ instead of directly specifying the whole path.. These keys work for my oci cli in my other instances, permissions dont matter correct? I usually do 777 as a bad habit, but had them at 600.. I ended up just destroying and going to recreate today.

**Comment by toxophilist** [comment]
@LotToLearn If you have created within an OCI instance you should just assign the VM to your Instance Principal group.

Also the docker logs usually give additional information on what caused the Internal Server Error can you check again.

**Comment by LotToLearn** [comment]
not sure what the issue was, but on a fresh docker it is working without changing anything. Good ol turn it on and off? But now it queries almost everything but my database in a private subnet, why might that be? Out of scope of this topic, so can make a new one. Looking at the logs it requests everything and includes database, but no failures or errors in logs.

**Comment by toxophilist** [comment]
@LotToLearn can you try turning off (deselect) fast discover in the preferences and see if the DB is displayed on query

**Comment by LotToLearn** [comment]
> @LotToLearn can you try turning off (deselect) fast discover in the preferences and see if the DB is displayed on query

@toxophilist I turned it off, and it didn't work and actually stopped showing my buckets and autonomous DB

**Comment by LotToLearn** [comment]
@toxophilist 
Fast discovery on (notice ADB / buckets)
![fast_discovery](https://user-images.githubusercontent.com/56550251/113888797-455cfb00-9788-11eb-8037-cf024e731fab.png)

fast discovery off (ADB / buckets gone)
![nofast_discovery](https://user-images.githubusercontent.com/56550251/113888884-586fcb00-9788-11eb-8d02-3e385ae9f7af.png)

**Comment by toxophilist** [comment]
Hmm odd I'll spend some more time trying to reproduce this

**Comment by toxophilist** [comment]
v0.21.0 release resolves the bucket subscription issue.
