### ISSUE TITLE
Cost estimation shows "Updated" and "OKIT version" as first 2 lines

### ISSUE THREAD

**Issue by jngithub1** [oracle/oci-designer-toolkit#270]
![OKIT bug cost estimate-1](https://user-images.githubusercontent.com/29753707/111318456-5f159180-8665-11eb-962d-024b78be7724.png)

**Comment by jngithub1** [comment]
Minor cosmetic issue but still a bug....

**Comment by toxophilist** [comment]
Fixed in 0.19.0 release
