### ISSUE TITLE
Validation issue: should not be able to choose Logical Volume Management when provisioning a RAC db in DBCS

### ISSUE THREAD

**Issue by jngithub1** [oracle/oci-designer-toolkit#271]
It will throw you off-base with a very weird "Error: Service error:InvalidParameter. Request is rejected because port 22 is not enabled in the ingress security list for subnet" when doing the apply. Took me a while to figure it out.
Should only allow ASM to be chosen when provisioning a RAC db in DBCS

**Comment by toxophilist** [comment]
Extreme Performance  / LVM test added to 0.19.0
