### ISSUE TITLE
Document Ehancement Request

### ISSUE THREAD

**Issue by philstepson** [oracle/oci-designer-toolkit#293]
I’m attempting to Load from Git unsuccessfully and have the following configuration on Okit 19.02 running on my Mac OS system:

config in ~/.ssh     follows:
 
***Host    github.com
        User philstepson
        Hostname github.com
        PreferredAuthentications publickey
        IdentityFile  ~/.ssh/pwsarchvm1.key***

Github allows me to authenticate to GitHub with my proper username:

***(base) pwstephe@PWSTEPHE-mac .ssh % ssh -T git@github.com
Hi philstepson! You’ve successfully authenticated, but GitHub does not provide shell access.***

My git_repositories file in ~/.oci looks like this:

***[repos]
branch = master*** <br>
***url = git@github.com:PSRepo***

I’m really not certain what the proper syntax of either the config file in .ssh or the git_repositories file in .oci should be to work with Okit.

Even though I seem to authenticate correctly Okit is not seeing my repository

Could the documentation be a little more specific about the options for these two configuration files?

**Comment by toxophilist** [comment]
@philstepson Will definitely take a look at improving the documentation

**Comment by LotToLearn** [comment]
@toxophilist Any update on this? Seems Phil & I are having the same issues

**Comment by toxophilist** [comment]
@philstepson @LotToLearn The examples I have in the README are taken directly from my system with the git_repositories file containing
```properties
[OKIT Community Templates]
branch=main
url=git@github.com:username/okit-community-templates.git
```

And my ssh config file

```config
TCPKeepAlive yes

Host *
	ServerAliveInterval 240
	ServerAliveCountMax 2
	TCPKeepAlive yes
	AddKeysToAgent yes
Host github.com
	IdentityFile ~/.ssh/id_rsa_github
```

If this is not working within the container can you check if the key is in the container ~/.ssh directory.
