### ISSUE TITLE
Shapes are wrongly reports

### ISSUE THREAD

**Issue by AnykeyNL** [oracle/oci-designer-toolkit#3]
A VMstandard shape show "undefined OCPU"
A E2.1 shape shows 4 OCPU -> this should be 1 OCPU or 2 vCPU
A VMstandard 1.1 shows 8 OPCU, should be 1
B1.1 show 2 should be 1
B1.6 shows 4 should be 16

etc...

**Comment by toxophilist** [comment]
I can't seem to reproduce this the information was downloaded from OCI and stored in a static json so it seems odd.

**Comment by toxophilist** [comment]
@AnykeyNL Can you try the 0.5.1 release to see if you still have the issue because I'm unable to reproduce. These values are pull before release from OCI.

**Comment by toxophilist** [comment]
Until we upgrade the oci python module I have removed the display of CPU / Memory. This will return in a future release.
