### ISSUE TITLE
Terraform option gives no response

### ISSUE THREAD

**Issue by Davidmh93** [oracle/oci-designer-toolkit#30]
When creating a terraform template of the design i've produced gives no response. Compartment names exist in my tenancy as well. 

Any info. on how I can debug this further? This is the error in the console:

POST http://localhost/okit/generate/terraform 500 (INTERNAL SERVER ERROR)

**Comment by toxophilist** [comment]
@Davidmh93 if you are running the docker version can you start it with the -it instead of -d and then execute the generate. You should then see what the server error is. If running the Vangrant you should be able to log in and check the log file in /okit/log. 

Can you then post the error.

**Comment by toxophilist** [comment]
@Davidmh93 Can you test this with the new 0.7.0 release
