### ISSUE TITLE
DB System and OKE within a compartment

### ISSUE THREAD

**Issue by agregory999** [oracle/oci-designer-toolkit#305]
Is it possible to create a compartment structure first, such as:
- root
- - network
- - DB
- - app

Then create a VCN in the network compartment and a DB System in the DB compartment, using the subnet that resides in the network compartment.  Seems it is requiring a VCN to be put inside of.

**Comment by javierbm7** [comment]
#246 I think is part of this issue

**Comment by toxophilist** [comment]
@agregory999 Current version is a bit prescribed but I'm working on making it more flexible. I'll try and get this in for the next release.

**Comment by capaaway** [comment]
Some news about this feature? I've the same need.
thanks!

**Comment by toxophilist** [comment]
Only the OKE is outstanding and this will be resolved as part of some rework planned on OKE

**Comment by toxophilist** [comment]
Resolved in 0.46.0
