### ISSUE TITLE
Terraform export should use multiple files

### ISSUE THREAD

**Issue by agregory999** [oracle/oci-designer-toolkit#308]
Would it be possible to have the export into .tf files use more of a modular approach?  All of what is exported currently goes into a single main.tf, but could be separated by function or as Terraform/ORM best practices advise.

**Comment by toxophilist** [comment]
I can take a look

**Comment by toxophilist** [comment]
Release v0.37.0 has this functionality with the TF resources split based on how the console splits the Resources
