### ISSUE TITLE
Some Instance Shapes are Missing 

### ISSUE THREAD

**Issue by sgmphil** [oracle/oci-designer-toolkit#312]
I have noticed that some instance shapes are missing. One example is VM.Standard.E2.1.Micro. I have a couple of these shapes running and when running a query, the query defaults the instances to BM.DenseIO2.52. If I were to push that config back to OCI, that would potentially cause some real headaches!

**Comment by toxophilist** [comment]
Odd these are queried from OCI when the page is opened and update the drop down options shipped with each release

**Comment by toxophilist** [comment]
@sgmphil This should be resolved in v0.24.0 if you select your connection profile associated with the free tier. The dropdown cache is updated on a per profile basis.
