### ISSUE TITLE
Bug: OKIT attempts to add defined_tags to oci_core_network_security_group_security_rule

### ISSUE THREAD

**Issue by agregory999** [oracle/oci-designer-toolkit#316]
Terraform only allows `defined_tags` at the `oci_core_vcn` and at the `oci_core_network_security_group` level, but not at the `oci_core_network_security_group_security_rule` level.  When OKIT queried an existing tenancy that had NSGs with rules, it somehow added the defined_tags to the terraform, then it fails with errors for each NSG Rule:

```
Error: Unsupported argument
  on main.tf line 293, in resource "oci_core_network_security_group_security_rule" "Cis2_Nsg_App_Rule2" 
 293:     defined_tags   = {"Oracle-Tags.CreatedBy"": ""oracleidentitycloudservice/andrew.gregory@oracle.com"", ""Oracle-Tags.CreatedOn"": ""2021-05-03T13:49:07.951Z"}
An argument named "defined_tags" is not expected here.
```

**Comment by toxophilist** [comment]
Fixed in 0.23.0 release
