### ISSUE TITLE
export to terraform local zip or ansible local zip is not working

### ISSUE THREAD

**Issue by xperiazn** [oracle/oci-designer-toolkit#347]
Hi,
Export to terraform local zip, ansible local zip or resource manager is not working.
Validation is successful no errors or warnings. When i click on export to terraform local file nothing happens. same with ansible local zip. Export to resource manager fails with error: "Export to Resource Manager Failed (INTERNAL SERVER ERROR)"
Can i debug somehow problem?
Kind regards

**Comment by toxophilist** [comment]
@xperiazn if you look at the Docker logs it should show you the error. If you paste it in a comment I'd appreciate it.

**Comment by xperiazn** [comment]
Only error in in docker log is this:

Same error is for ansible local zip and terraform local zip

INFO: Processing OKE Cluster Information Covidcluster
ERROR: 'image'
Traceback (most recent call last):
  File "/okit/okitweb/okitWebDesigner.py", line 333, in generate
    generator.generate()
  File "/okit/visualiser/generators/okitGenerator.py", line 197, in generate
    self.renderOkeCluster(oke)
  File "/okit/visualiser/generators/okitGenerator.py", line 1395, in renderOkeCluster
    jinja2_pool["node_source_details"]["image"] = self.generateJinja2Variable('node_pool_{0:02d}_image'.format(pool_number), pool["node_source_details"]["image"], standardisedName)
KeyError: 'image'

**Comment by toxophilist** [comment]
@xperiazn do you still have this issue.

**Comment by toxophilist** [comment]
Closed due to no response to previous message. If this is still an issue please reopen.
