### ISSUE TITLE
Cannot create multiple Compartments at root (v0.22.1)

### ISSUE THREAD

**Issue by jeliker** [oracle/oci-designer-toolkit#349]
Regularly, will define environment with two root-level Compartments (i.e. App1, App2) but cannot seem to do that with current release.

Tried first creating nested, saving, editing json and setting "compartment=null" for second, the reloading. Almost works but display is mangled trying to render both side-by-side (or stacked or whatever)

**Comment by toxophilist** [comment]
@jeliker if you create you designer with 2 sub compartments and then deploy to the root does this not work.
