### ISSUE TITLE
Database System Password needs to be validated

### ISSUE THREAD

**Issue by markmundy** [oracle/oci-designer-toolkit#362]
The current OKIT version can fail to create a database system because the sys password chosen does not conform to the standard required. There needs to be validation on the given password to ensure it complies with policy. 

Without validation it is possible to have a DB system fail to build in OCI.

Currently 'Password must be 9 to 30 characters and contain at least 2 uppercase, 2 lowercase, 2 special, and 2 numeric characters. The special characters must be _, #, or -.'

**Comment by toxophilist** [comment]
Passwords will now only allow variable entry to mandate no passwords are stored in model.
Added to OCD [Release](https://github.com/oracle/oci-designer-toolkit/releases)
