### ISSUE TITLE
Vagrant URL has changed

### ISSUE THREAD

**Issue by meerkat2u** [oracle/oci-designer-toolkit#37]
Vagrantfile in oracle/oci-designer-toolkit/containers/vagrant refers to 
URL https://oracle.github.io/vagrant-boxes/boxes/oraclelinux/7.json which doesn't exist
Valid URL appears to be https://oracle.github.io/vagrant-projects/boxes/oraclelinux/7.json

**Comment by toxophilist** [comment]
@meerkat2u this will be fixed in the 0.8.0 release
