### ISSUE TITLE
Vagrant does not work the second time

### ISSUE THREAD

**Issue by Rinjhin** [oracle/oci-designer-toolkit#39]
I followed the instructions for creating a Vagrant image and it worked successfully the first time.  However, when I ran today with 'vagrant up; vagrant ssh', and I navigated to http://localhost/okit/designer on my browser, it gives me Internal Server Error.  After I built the image, I see the following that the okit folder is empty:
[vagrant@okit-vagrant ~]$ ls
okit
[vagrant@okit-vagrant ~]$ cd okit/
[vagrant@okit-vagrant okit]$ ls
[vagrant@okit-vagrant okit]$ hostname
okit-vagrant
[vagrant@okit-vagrant okit]$ whoami
vagrant
[vagrant@okit-vagrant okit]$
Am I missing something here?  Or did something get deleted?

**Comment by toxophilist** [comment]
@Rinjhin have you upgraded okit between creating the Vagrant image and running it today.

**Comment by Rinjhin** [comment]
No I have not upgraded okit since my initial download from github back in May.  Should I download the GIT Repository once again, and re-install Vagrant on top of Virtual Box?

**Comment by toxophilist** [comment]
@Rinjhin I would recommend you do that. The build process has changed slight so that it copies all the files into the image rather than link them. Check out the new instructions once you have pulled the latest.

**Comment by Rinjhin** [comment]
I have pulled the latest version of oci-designer-toolkit.git today from github.  I re-installed my Virtual Box, Vagrant and re-created vagrant image.  But I got the same Internal Server Error in the browser when I type: http://localhost/okit/designer.  Also the vagrant user's home directory is still empty:
[vagrant@okit-vagrant okit]$ cd
[vagrant@okit-vagrant ~]$ ls
[vagrant@okit-vagrant ~]$ pwd
/home/vagrant
[vagrant@okit-vagrant ~]$
But I am not sure if the above makes any difference.  When I do:
  ps -ef | grep okit
vagrant   1268  1216  0 00:09 pts/0    00:00:00 grep --color=auto okit
root      2846     1  0 Jul08 ?        00:00:00 /sbin/dhclient -q -lf /var/lib/dhclient/dhclient--eth0.lease -pf /var/run/dhclient-eth0.pid -H okit-vagrant eth0
My installation of image was done successfully.  What am I missing here?  Please help.

**Comment by toxophilist** [comment]
@Rinjhin If you ssh into the vagrant image you should be able to cd to /okit/logs. The okit.log in this directory should given you more information on what the issue is.

**Comment by webfrasse** [comment]
@Rinjhin There is no need to re-install Virtualbox or Vagrant. Remove the OKIT vagrant build with vagrant destroy from the same folder where you ran vagrant up

All you need to do is clone the latest OKIT. You can actually remove the old clone you downloaded and just download the latest, or put it in a new location and do vagrant up.

**Comment by webfrasse** [comment]
You can run _vagrant global-status_ from any location on your machine and it will list all vagrant instances. Sample output on my mac:

_vagrant global-status
id       name         provider   state    directory
--------------------------------------------------------------------------------------------------------------
b2cf7f8  oci          virtualbox poweroff /Users/mfransso/VirtualMachines/MyVagrants/MyOCI
21f9bcc  vpn          virtualbox poweroff /Users/mfransso/VirtualMachines/MyVagrants/VPN-template
1476435  myvpn        virtualbox running  /Users/mfransso/VirtualMachines/MyVagrants/MyVPN
81b7c20  apex         virtualbox poweroff /Users/mfransso/VirtualMachines/MyVagrants/OracleAPEX20.1
24b5985  okit-vagrant virtualbox running  /Users/mfransso/Work/github/oci-designer-toolkit/containers/vagrant
1c5cce2  ol7          virtualbox poweroff /Users/mfransso/VirtualMachines/VagrantTests/ol7-gui

The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date (use "vagrant global-status --prune" to prune invalid
entries). To interact with any of the machines, you can go to that
directory and run Vagrant, or you can use the ID directly with
Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"_
