### ISSUE TITLE
Pulling the repo can be done via HTTPS too

### ISSUE THREAD

**Issue by andytael** [oracle/oci-designer-toolkit#4]
Cloning the repo can be done via HTTPS too. I have issues using ssh and github so I used the following:

`git clone -b v0.5.0 --depth 1 https://github.com/oracle/oci-designer-toolkit.git`

**Comment by ywvliu** [comment]
thanks. got the same issues and resolve by using https.

**Comment by toxophilist** [comment]
Updated Installation document to show both clone alternatives.
