### ISSUE TITLE
Sub-Menu options can't be selected in Chrome

### ISSUE THREAD

**Issue by rizwanarshad1980** [oracle/oci-designer-toolkit#406]
Hi,

In Chrome, navigating to the hamburger menu > Export > Terraform the "Local Zip" and "Git" options appear detached from the menu and cannot be easily accessed.

In Safari the sub-menu is initially detached from the main menu and then connects to the main menu allowing the options to be easily selected.

I'm using V0.24.0 (7th July 2021)

Thanks

![chrome](https://user-images.githubusercontent.com/79280702/124903529-f5d2d900-dfdb-11eb-86af-03bc0582457b.png)

**Comment by toxophilist** [comment]
@rizwanarshad1980 this is usually associated with a scroll issue and can often be resolved by maximising your browsers / closing any download information / zooming the view.

I will be working on a resolution to this issue although I have never managed to reproduce it.

**Comment by rizwanarshad1980** [comment]
@toxophilist - thanks - maximising the browser does resolve the problem

**Comment by toxophilist** [comment]
@rizwanarshad1980 I added some adjustment to the 0.25.0 release to remove scrollbar width from placement so hopefully this should resolve the issue.
