### ISSUE TITLE
all compute shapes are displayed with shape "BM.DenseIO2.52" with update okit 0.24.5

### ISSUE THREAD

**Issue by LorenzKeller** [oracle/oci-designer-toolkit#432]
Dear,
after upgrade to okit 0.24.5 all compute shapes when querying are displayed with shape "BM.DenseIO2.52" although other shapes are in use.
Kind regards
Lorenz

**Comment by toxophilist** [comment]
@LorenzKeller Sorry I can not reproduce this. Can you try refreshing the cache from the menu. This will force a re-download of the dropdown data for the selected connection profile.
