### ISSUE TITLE
OKIT fails to build (docker build)  in OCI Compute (Linux) . Please help to fix the Dockerfile

### ISSUE THREAD

**Issue by wuyingki** [oracle/oci-designer-toolkit#433]
Compute VM (Oracle Linux 7.8) in OCI:

Step0) Sudo su -

Step1) Git Clone master branch to /home/opc/, with below command:
git clone -b master --depth 1 https://github.com/oracle/oci-designer-toolkit.git

Step2) cd /home/opc/oci-designer-toolkit

Step3) docker build --tag okit --file /home/opc/oci-designer-toolkit/containers/docker/Dockerfile  --force-rm /home/opc/oci-designer-toolkit/containers/docker/

Error below:

Sending build context to Docker daemon  17.92kB
Step 1/17 : FROM oraclelinux:7-slim
 ---> 0a28ba78f4c9
Step 2/17 : LABEL "provider"="Oracle"       "issues"="https://github.com/oracle/oci-designer-toolkit/issues"       "version"="0.24.5"       "description"="OKIT Web Server Container."       "copyright"="Copyright (c) 2020, 2021, Oracle and/or its affiliates."
 ---> Using cache
 ---> a061000e04ab
Step 3/17 : SHELL ["/bin/bash", "-c"]
 ---> Using cache
 ---> c660b3552c0c
Step 4/17 : ENV PYTHONIOENCODING=utf8     PYTHONPATH=":/okit/visualiser:/okit/okitweb:/okit"     FLASK_APP=okitweb     FLASK_DEBUG=1     LANG=en_GB.UTF-8     LANGUAGE=en_GB:en     LC_ALL=en_GB.UTF-8     PATH=/root/bin:${PATH}
 ---> Using cache
 ---> 3da95ff2cb93
Step 5/17 : EXPOSE 80
 ---> Using cache
 ---> 3e6628f1e0a5
Step 6/17 : EXPOSE 443
 ---> Using cache
 ---> 81ff1742ae4e
Step 7/17 : RUN yum install -y     oracle-softwarecollection-release-el7     oraclelinux-developer-release-el7  && yum-config-manager --disable ol7_ociyum_config  && yum update -y  && yum install -y         git         openssl         python36         python3-pip  && rm -rf /var/cache/yum  && python3 -m pip install --upgrade pip  && pip3 install --no-cache-dir         authlib==0.15.3         flask==1.1.2         gitpython==3.1.14         git-url-parse==1.2.2         gunicorn==20.0.4         oci         openpyxl==3.0.7         pandas==1.1.2         python-magic==0.4.22         pyyaml==5.4.1         requests==2.25.1         xlsxwriter==1.3.7  && mkdir -p /okit/{config,git,log,ssl,visualiser,okitweb,workspace,templates,skeletons}  && mkdir -p /okit/okitweb/static/okit/templates  && openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /okit/ssl/okit.key -out /okit/ssl/okit.crt -subj "/C=GB/ST=Berkshire/L=Reading/O=Oracle/OU=OKIT/CN=www.oci_okit.com"  && ln -s /okit/templates /okit/okitweb/static/okit/templates/user  && ln -s /okit/git /okit/okitweb/static/okit/templates/git  && ln -s /okit/git /okit/okitweb/static/okit/git
 ---> Using cache
 ---> 02dc2bc81a3f
Step 8/17 : COPY config /okit/config
COPY failed: stat /var/lib/docker/tmp/docker-builder150620664/config: no such file or directory

**Comment by toxophilist** [comment]
@wuyingki When building an OCI image there is a specific section within the installation instructions for this that does not use docker. This is because we can hook into the uname/pwd for OCI and docker on OL is rather old and as you see has issues.
