### ISSUE TITLE
Github branch hygience

### ISSUE THREAD

**Issue by davidkhala** [oracle/oci-designer-toolkit#453]
![image](https://user-images.githubusercontent.com/7227589/132473959-bedbd167-681c-4eca-ad10-0310b942fc01.png)

Now we have quite a few merged, closed or stale branches. 

Can maitainers help to delete them if not to use anymore?

**Comment by toxophilist** [comment]
@davidkhala There is a strategy for some of the branch for instance the ones labeled v0*.* will remain until the subsequent release has been merged. For the stale branches I agree we do need the owners to clean then.

**Comment by toxophilist** [comment]
Cleaned stale branches
