### ISSUE TITLE
Docker artifact/release availability in container registry

### ISSUE THREAD

**Issue by davidkhala** [oracle/oci-designer-toolkit#456]
According to README, I see the only way to run OKIT is to build docker by our own from source. 

Is it possible we publish a ready to use docker image to a docker registry somewhere? anyone of
- GHCR(Github Container Registry), like https://github.com/oracle/container-images/pkgs/container/oraclelinux
- Dockerhub
- Oracle Container Registry

**Comment by toxophilist** [comment]
@davidkhala It's on the roadmap

**Comment by toxophilist** [comment]
Given the changes to Docker desktop charging I will be dropping docker as a deployment solution and switching to a desktop version.

**Comment by davidkhala** [comment]
> Given the changes to Docker desktop charging I will be dropping docker as a deployment solution and switching to a desktop version. 

please consider those users like me not using docker desktop but docker for Linux including Ubuntu and even podman as alternative on Oracle Linux.


they always get benefit from docker image on registry
