### ISSUE TITLE
Connection to OCI not working on OKIT v26

### ISSUE THREAD

**Issue by kayodeOluwafmi** [oracle/oci-designer-toolkit#461]
Just installed OKIT v26. config has my tenancy details .

Am attempting to use the **Export to Resource Manager** capability in OKIT, to push a simple design to my tenancy 
1) OKIT is picking up my tenancy details from the config file
2) but OKIT is not showing any values for the **Region** drop down
3) and OKIT is not showing any values for the **Compartment** drop down.

Is there something am missing? Please advise.

**Comment by toxophilist** [comment]
@kayodeOluwafmi this sounds like the config file entry is not correct the usual issues with this is the key file location not pointing to ~/.oci/<key_file_name>

**Comment by kayodeOluwafmi** [comment]
Below is my config entry and hosting docker startup command.

**##Config entry for key file**
..............
_region=uk-london-1_
_key_file=/home/opc/oci-designer-toolkit/containers/oci/oci_api_key.pem_
..............

**##Docker startup command**
_export OKIT_ROOT_DIR=/home/opc/oci-designer-toolkit_
_export OCI_CONFIG_DIR=$OKIT_ROOT_DIR/containers/oci_ 

_sudo docker run -d --rm -p 80:80 --name okit  --hostname okit -v $OCI_CONFIG_DIR:/root/.oci -v $OKIT_ROOT_DIR/okitweb:/okit/okitweb -v $OKIT_ROOT_DIR/visualiser:/okit/visualiser -v $OKIT_ROOT_DIR/log:/okit/log okit_

As you can see i've specified the path location to the key file and this in specified for docker startup. Anu ideas?

**Comment by toxophilist** [comment]
@kayodeOluwafmi the key_file entry needs to point to the location within the docker container which will be ~/.oci/oci_api_key.pem

**Comment by jeliker** [comment]
There are other operations/applications/tools that require `key_file` be an absolute path (perhaps VirtualBox but I can't recall?) so I've set all my `key_file` entries to absolute. I suppose the solution is to add a duplicate entry in `~/.oci/config`

```
[someprof]
user = ocid1.user.oc1..blahblahblahyaddayaddayaddablahblahblahyaddayaddayadda
fingerprint = 08:67:53:09:08:67:53:09:08:67:53:09
key_file = /home/me/.oci/oci_api.pem
tenancy = ocid1.tenancy.oc1.. blahblahblahyaddayaddayaddablahblahblahyaddayaddayadda
region = us-ashburn-1

[someprof-okit]
user = ocid1.user.oc1..blahblahblahyaddayaddayaddablahblahblahyaddayaddayadda
fingerprint = 08:67:53:09:08:67:53:09:08:67:53:09
key_file = ~/.oci/oci_api.pem
tenancy = ocid1.tenancy.oc1.. blahblahblahyaddayaddayaddablahblahblahyaddayaddayadda
region = us-ashburn-1
```

**Comment by jeliker** [comment]
Had some inspiration and found this as an alternative to above second profile:  Start docker with extra volume statement mapping `/home/me/.oci` to `/home/me/.oci`

```
docker run -d --rm -p 80:80 \
--volume /home/me/.oci:/root/.oci \
--volume /home/me/.ssh:/root/.ssh \
--volume /home/me/.oci:/home/me/.oci \
--name okit okit
```

**Comment by toxophilist** [comment]
Closed due to no response if this issue still exist with latest version please reopen
