### ISSUE TITLE
Allowing for DRG with Multiple Attachments

### ISSUE THREAD

**Issue by DanielBatesJ** [oracle/oci-designer-toolkit#483]
Our team is currently using Version 0.26.0 of Okit for a customer engagement and the DRG does not seem to support [multiple attachments](https://docs.oracle.com/en-us/iaas/Content/Network/Tasks/managingDRGs.htm). From checking the changelog this doesn't seem to have changed for the latest version.

From what I can tell, this is a new feature on OCI as of May of 2021 so any information you can share on plans to add this functionality would be great, and of course if I'm missed something obvious feel free to correct me.

**Comment by toxophilist** [comment]
@DanielBatesJ This is now available with the 0.29.0 release.
