### ISSUE TITLE
[SSL: TLSV1_ALERT_ACCESS_DENIED] when using OCI Toolkit in Amsterdam region - does work in Frankfurt

### ISSUE THREAD

**Issue by mfokkergit** [oracle/oci-designer-toolkit#491]
I have two tenants (one with home region Frankfurt and one with home region Amsterdam). 
After some troublshooting I concluded the the Amsterdam region is not working in the toolkit (not sure if this is a toolkit / Oracle or other issue :))

It keeps retrieving info. The console shows
File "/usr/local/lib/python3.6/site-packages/oci/base_client.py", line 536, in request
raise exceptions.RequestException(e)
oci.exceptions.RequestException: OCIConnectionPool(host='objectstorage.eu-amsterdam-1.oraclecloud.com', port=443):
Max retries exceeded with url: /n (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:877)'),))

When using the Frankfurt tenant this does work. I've added the Amsterdam region to this tenant (so I can switch between Frankfurt and Amsterdam, but even then the Amsterdam tenant does not work. The same error pops up)

Any ideas?

Regards,
Marcel

**Comment by toxophilist** [comment]
This is not an OKIT issue but is likely to be associated with the policy / privileges associated with the account.
