### ISSUE TITLE
Version: 0.30.0 (1st December 2021) - Issues with adding an Instance compute to VCN

### ISSUE THREAD

**Issue by jaalsuca** [oracle/oci-designer-toolkit#502]
Hi there

I am not sure if this would be considered a bug. But, the deployed OKIT version doesn´t allow me to add a Computer instance into the VCN. Also, the information from my OCI Infrastructure is not retrieving as well. 

Would you please put instructions on how to get OCI Infrastructure or multiple regions infrastructure ? 

I followed each step by step instruction.

**Comment by toxophilist** [comment]
@jaalsuca Instances can only be dropped on a subnet or compartment. Existing infrastructure is retrieved using the query menu item

**Comment by jaalsuca** [comment]
Hi @toxophilist 

Could you please be a bit specific? I know and it is quite logical to retrieve current infrastructure from the query menu. 

Now, I can see a new version but the documentation does not specify how to update it.

Regards;

Jairo Suarez

**Comment by jaalsuca** [comment]
How to be specific when someone requires help. 
If you already have OKIT installed and you want to update it. Please follow these steps.

I am using Oracle Linux as OS

PATH=$PATH:$HOME/.local/bin:$HOME/bin
OKIT_DIR=/okit
export OKIT_DIR
export PATH
[opc@okit-server02 ~]$ sudo systemctl stop gunicorn.service
[opc@okit-server02 ~]$ cd /okit/
[opc@okit-server02 okit]$ ls

[opc@okit-server02 okit]$ git pull
error: cannot open .git/FETCH_HEAD: Permission denied

[opc@okit-server02 okit]$ sudo git pull
remote: Enumerating objects: 21781, done.
remote: Counting objects: 100% (21781/21781), done.
remote: Compressing objects: 100% (5957/5957), done.
remote: Total 21385 (delta 15170), reused 20169 (delta 14232), pack-reused 0
Receiving objects: 100% (21385/21385), 7.48 MiB | 12.55 MiB/s, done.
Resolving deltas: 100% (15170/15170), completed with 207 local objects.
From https://github.com/oracle/oci-designer-toolkit
   84d7149..a55ccfa  master     -> origin/master
 * [new tag]         v0.30.1    -> v0.30.1
From https://github.com/oracle/oci-designer-toolkit
 * [new tag]         v0.10.0    -> v0.10.0
 * [new tag]         v0.10.1    -> v0.10.1
 * [new tag]         v0.10.2    -> v0.10.2
 * .........
 * ...............
 * ........................
 *  visualiser/query/ociRegionQuery.py                    |   8 ++-
 visualiser/templates/terraform/copyright.jinja2       |   4 ++
 visualiser/templates/terraform/provider.jinja2        |   4 --
 visualiser/templates/terraform/region_data.jinja2     |  13 -----
 32 files changed, 515 insertions(+), 296 deletions(-)
 create mode 100644 okitweb/okitExport.py
 create mode 100644 okitweb/static/okit/view/terraform/css/view.css
 create mode 100644 okitweb/static/okit/view/terraform/js/view.js
 create mode 100644 visualiser/templates/terraform/copyright.jinja2

[opc@okit-server02 oci]$ sudo systemctl start gunicorn.service

**Comment by jaalsuca** [comment]
After successful update of OKIT, I am still confused in regards of add into the deployment compartment by default, a new VCN, into the new VCN should include a Compute Instance or Analytics instance but I am now allowed to do it., why?

![image](https://user-images.githubusercontent.com/40186554/146655881-3858840b-51dc-4313-9f8c-0ed17d4f0828.png)

**Comment by jaalsuca** [comment]
After successful update of OKIT. I am still fighting to retrieve information from my OCI Infrastructure.
![image](https://user-images.githubusercontent.com/40186554/146656590-7ca6f4a1-4b98-4ba7-bb8c-5f972ce8c2b2.png)

If you please can offer specific information where I must modify the config file, I much really appreciate it.

3 things basic steps I have done.
First, follow the documentation here https://github.com/oracle/oci-designer-toolkit/blob/master/documentation/Installation.md#config-file

Second, copy the config file here /okit/containers/oci
Third, copy and modify the file here /okit/config/config with different tittle, I put ADMIN.

The result is the same as per showed above.

Jairo

**Comment by toxophilist** [comment]
@jaalsuca This is usually an issue with the config file key file entry 

Can you log into the container 

docker exec -it okit bash
cat ~/.oci/config
It should show 'key_file=~/.oci/oci_api_key.pem' and the file has to be in the '/root/.oci' directory.

The entry should be something similar to that above with the file in ~/.oci

**Comment by toxophilist** [comment]
Closed due to no recent update
