### ISSUE TITLE
(Save to Github) is now working [BUG] !

### ISSUE THREAD

**Issue by mahmoudrabie** [oracle/oci-designer-toolkit#507]
- **Version:** 0.30.1 (9th December 2021)

- **Performed Steps** as per detailed installation guide:
1. create the git_repositories file
2. private/public key files exist within your <USER HOME DIR>/.ssh
3. defines the key/url mapping in <USER HOME DIR>/.ssh/config 
4. write config file as the following

```
TCPKeepAlive yes

Host *
  ServerAliveInterval 240
  ServerAliveCountMax 2
  TCPKeepAlive yes
  AddKeysToAgent yes

Host github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_ed25519
```

**- Steps to reproduce**
1. Open OKIT designer
2. Save to Git
3. See entry of github and select it
4. write design json filename
5. Nothing saved to github repo !

I would appreciate any help or recommendations
@toxophilist 
@scross01

**Comment by toxophilist** [comment]
@mahmoudrabie Following the save to git do you see it in the git tab on the left of the screen. 

Also do you see any errors in the okit log file / docker console log.

Finally can you open a terminal connection to the docker container and confirm you can connect to github and clone your repo

**Comment by philstepson** [comment]
Andrew,

Following your advice and checking the log I did see an error in the log.
Next, I attempted to connect to GitHub from the container command line 
and receive the following:

    bash-4.2# *ssh github*
    The authenticity of host 'github.com (140.82.112.4)' can't be
    established.
    ECDSA key fingerprint is
    SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
    ECDSA key fingerprint is
    MD5:7b:99:81:1e:4c:91:a5:0d:5a:2e:2e:80:13:3f:24:ca.
    Are you sure you want to continue connecting (yes/no)? *yes*
    Warning: Permanently added 'github.com,140.82.112.4' (ECDSA) to the
    list of known hosts.
    PTY allocation request failed on channel 0

    Hi philstepson! You've successfully authenticated, but GitHub does
    not provide shell access.
    Connection to github.com closed.


Seems like when there is an attempt to connect with a new fingerprint 
for a unique instance of a container that we wouldn't see this message 
to respond 'yes' to unless we are in the container itself.

Thanks,
Phil

Untitled Document **
*Phil Stephenson*
**
Saint Louis, MO US

*

*

**Comment by mahmoudrabie** [comment]
Thanks a lot @toxophilist for your prompt response

I have checked the container log and found the following error
```
ERROR: Cmd('git') failed due to: exit code(128)

  cmdline: git clone --branch=main --no-single-branch -v git@github.com:mahmoudrabie/my-private-repo.git /okit/instance/git/github.com/my-private-repo

  stderr: 'Host key verification failed.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights

and the repository exists.

'

Traceback (most recent call last):

  File "/okit/okitweb/okitWebDesigner.py", line 426, in git_panel

    repo = Repo.clone_from(url, git_repo_dir, branch=branch, no_single_branch=True)

  File "/usr/local/lib/python3.6/site-packages/git/repo/base.py", line 1032, in clone_from

    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)

  File "/usr/local/lib/python3.6/site-packages/git/repo/base.py", line 973, in _clone

    finalize_process(proc, stderr=stderr)

  File "/usr/local/lib/python3.6/site-packages/git/util.py", line 329, in finalize_process

    proc.wait(**kwargs)

  File "/usr/local/lib/python3.6/site-packages/git/cmd.py", line 408, in wait

    raise GitCommandError(self.args, status, errstr)

git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)

  cmdline: git clone --branch=main --no-single-branch -v git@github.com:mahmoudrabie/my-private-repo.git /okit/instance/git/github.com/my-private-repo

  stderr: 'Host key verification failed.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights

and the repository exists.

'
```

I would appreciate your advice

**Comment by toxophilist** [comment]
@mahmoudrabie try adding the following to your ssh config

Host * 
     StrictHostKeyChecking no  
     UserKnownHostsFile=/dev/null

**Comment by mahmoudrabie** [comment]
Thanks a lot, @toxophilist for your support

I have added the lines above and here is my config file

> TCPKeepAlive yes
> 
> Host *
>   StrictHostKeyChecking no
>   UserKnownHostsFile=/dev/null
>   ServerAliveInterval 240
>   ServerAliveCountMax 2
>   TCPKeepAlive yes
>   AddKeysToAgent yes
> Host github.com
>   HostName github.com
>   User git
>   IdentityFile ~/.ssh/id_ed25519

then I have restarted the okit container and found the following error before going to call (save to GitHub) function

> ERROR: Cmd('git') failed due to: exit code(128)
> 
>   cmdline: git clone --branch=main --no-single-branch -v git@github.com:mahmoudrabie/my-private-repo.git /okit/instance/git/github.com/my-private-repo
> 
>   stderr: 'Host key verification failed.
> 
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

Any help or recommendations are more than welcome

**Comment by toxophilist** [comment]
@mahmoudrabie Did you do this  in the container if so a restart will erase it. You can edit your external file and rebuild

**Comment by mahmoudrabie** [comment]
Thanks a lot @toxophilist for your support

I have completed the following steps again:
(1) Review and update the.ssh/known_hosts
(2) Update the .ssh/config (UserKnownHostsFile ~/.ssh/known_hosts)
(3) Generate a new SSH key
(4) Update .ssh/config with the new key
(5) Add the key using ssh-add
(6) Add the new SSH key to your GitHub account
(7) Test the successful connection to Github using the following commad (ssh -T git@github.com)

Now, it is working fine
