### ISSUE TITLE
0.31.1 not pulling tenancy data

### ISSUE THREAD

**Issue by henremurr** [oracle/oci-designer-toolkit#511]
After upgrading to latest version, when I push design to Resource Manager the job fails. It seems that the terraform.zip file being pushed out does not contain any configuration data for the tenancy. When I roll back to 0.29.0, all works and the config data is present. All other Designer Toolkit functionality (in use) appears to be working correctly. If it makes any difference, I am querying/deploying to the Government version of OCI. Let me know if you need any log files, or anything else to help debug and resolve. Regards.

**Comment by toxophilist** [comment]
Does this still happen with the latest release

**Comment by henremurr** [comment]
Will check later today and let you know — regards

Merci beaucoup 👨‍🎨

**Comment by toxophilist** [comment]
@henremurr Can I close this issue or do you still see the problem

**Comment by toxophilist** [comment]
Closed assuming that this has been resolved if not please reopen
