### ISSUE TITLE
resizing canvas and up down scrollbar

### ISSUE THREAD

**Issue by DoubleUP66** [oracle/oci-designer-toolkit#513]
When using it with Firefox or Safari, the up- down scrollbar for the design canvas is missing. 
It is possible to zoom in or out, but when having zoomed out to see the bottom of the design and I add a component it jumps back to its original zoom size and the bottom part is not visible anymore.
I just downloaded the 0.32 version. Using one of the above browsers on MacOS.

**Comment by toxophilist** [comment]
You can also drag the canvas up to see the bottom. I'll take a look at keeping the pan and zoom when dropping resources

**Comment by toxophilist** [comment]
Resize resolved in 0.34
