### ISSUE TITLE
v0.33.0 (2nd March 2022) Canvas never initializes (trying Safari 15.4, Firefox 98)

### ISSUE THREAD

**Issue by jeliker** [oracle/oci-designer-toolkit#517]
Javascript console shows error "Subnet is not defined"

Failure appears to be compartment.js line 80

return [Compartment.getArtifactReference(), VirtualCloudNetwork.getArtifactReference(), Subnet.getArtifactReference(), ExadataInfrastructure.getArtifactReference()];

Error does not show from MS Edge 99

**Comment by toxophilist** [comment]
@jeliker This should be resolved in the 0.34. release can you please try and let me know if this is still an issue.

**Comment by toxophilist** [comment]
@jeliker Do you still see this issue with the latest release.

**Comment by jeliker** [comment]
Looks good! Just tested again in Safari and all is well.

Thank you.
