### ISSUE TITLE
Labels are cut off (consider font size, left justified, wrapping)

### ISSUE THREAD

**Issue by jeliker** [oracle/oci-designer-toolkit#523]
Display Names are cut off on all resources making it more difficult to use for documentation purposes. Please consider offering font size/face option, left justification (since left of text is more useful than the middle for knowing what it says), or wrapping (hard at a character boundary vs. word breaks).

![image](https://user-images.githubusercontent.com/590333/165305215-2a78aa8f-c180-4fc3-a60d-97ca539b1dd8.png)

**Comment by toxophilist** [comment]
Increase display width when labels are shown.
