### ISSUE TITLE
OKIT query to PCA X9 3.0.1 - Endpoint overriden is needed 

### ISSUE THREAD

**Issue by nuinattapon** [oracle/oci-designer-toolkit#531]
Hi team, 

I am trying to use OKIT with PCA X9. Unfortunately, the query function doesn't work because the ENDPOINT we have in PCA is diffrent to OCI. Do we have any documents showing all the parameter to set if we wanna use different end point.

I have built the DOCKER image using OKIT version 0.37.0. I run it using OCI parameters which works with oci cli. But it seems that the end point can not be overriden using the given parameters.

Here is my docker run script:

```
docker run -d --restart=unless-stopped \
  -p 8081:80 \
  --volume ~/.oci:/root/.oci --volume ~/.ssh:/root/.ssh \
  -e OCI_CLI_CERT_BUNDLE="~/.oci/pca.example.ca-chain.cert.pem" \
  -e OCI_CLI_TENANCY="ocid1.tenancy.AK00661530.pca.fqupz5ncsllv90s2im2quucdvmrzbh189exbktiwxm6dxb0sjkak00090146" \
  -e OCI_CLI_PROFILE="FIELD" \
  -e OCI_CLI_ID_ENDPOINT="https://identity.pca.example.com:30003/20160918" \
  -e OCI_CLI_IAAS_ENDPOINT="https://iaas.pca.example.com:30003/20160918" \
  -e OCI_CLI_COS_ENDPOINT="https://objectstorage.pca.example.com/oci" \
  -e OCI_CLI_FS_ENDPOINT="https://filestorage.pca.example.com:30003/20171215" \
  -e OCI_CLI_ENDPOINT="https://identity.pca.example.com:30003/20160918" \
  -e OCI_CLI_AUTH="api_key"  \
  --name okit gcr.io/nattapon/okit:0.37.0
```

Here us the error from `docker logs -f okit` showing that okit tried to connect to identity.pca.example.com port 443 not https://identity.pca.example.com:30003 :

`oci._vendor.requests.exceptions.SSLError: (MaxRetryError("OCIConnectionPool(host='identity.pca.example.com', port=443): Max retries exceeded with url: /20160918/tenancies/ocid1.tenancy.AK00661530.pca.fqupz5ncsllv90s2im2quucdvmrzbh189exbktiwxm6dxb0sjkak00090146 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),))",), 'Request Endpoint: GET https://identity.pca.example.com/20160918/tenancies/ocid1.tenancy.AK00661530.pca.fqupz5ncsllv90s2im2quucdvmrzbh189exbktiwxm6dxb0sjkak00090146 See https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdk_troubleshooting.htm for help troubleshooting this error, or contact support and provide this full error message.')`

**Comment by toxophilist** [comment]
@nuinattapon the cert needs to be specified in the config file by using the entry:

cert-bundle=~/.oci/certs/ca.crt

**Comment by nuinattapon** [comment]
@toxophilist ,
The issue is still there. OKIT is still trying go through port 443 not 30003.
Actually, I have already specify it using   -e OCI_CLI_CERT_BUNDLE="~/.oci/sca15-1070-scasg-bast.us.oracle.com.ca-chain.cert.pem"

**Comment by toxophilist** [comment]
@nuinattapon Is your cert up-to-date for that machine.

Also can you remove your detailed connection information from this ticket. This would be better dealt with on the internal Slack channel.

OKIT does not do anything specific with the environment overrides because the underlying oci api, used by OKIT, deals with them.

**Comment by nuinattapon** [comment]
@toxophilist Done per your request. 
For this case, how could we configure OKIT to explore resources on PCA if we could not override the end points.
