### ISSUE TITLE
Move between Designer and BOM mode

### ISSUE THREAD

**Issue by tassamartz** [oracle/oci-designer-toolkit#544]
Sometimes once moved to BOM mode, clicking on designer mode does not work, it remains open on BOM, only solution is to refresh the spa.

**Comment by toxophilist** [comment]
@tassamartz I can't actually reproduce this. Following any update of OKIT a Hard refresh when in the designer often help forcing all the javascript to be refreshed. If this happens again can you please check the development tools console for any errors.

**Comment by tassamartz** [comment]
@toxophilist i have checked with the latest version, i am not facing the issue with firefox anymore. it might be related to a refresh as you described. i am closing the issue.
