### ISSUE TITLE
Oracle Database version

### ISSUE THREAD

**Issue by tassamartz** [oracle/oci-designer-toolkit#552]
when selecting the Oracle Database element (Oracle Database Cloud VM), the versions displayed in the version choice list are:
11.2.0.4
12.1.0.2
12.2.0.1
18.0.0.0
19.0.0.0
21.0.0.0

I believe those are mapped to the latest of 11g, 12cR1, 12cR2, 18c, 19c, and 21c ? but misleading since for the 19c for example the latest is 19.17.0.0, for 21c, the latest is 21.8.0.0

**Comment by toxophilist** [comment]
These values are read from the OCI tenancy and cached in the browser. The caches can be refreshed from the main menu.
