### ISSUE TITLE
Network Security Group - compute instance "Show Connections" not making the link visible

### ISSUE THREAD

**Issue by tassamartz** [oracle/oci-designer-toolkit#553]
Case 1 OK : Create a network security group, attach it to a load balancer and check the box "show connection", the link between the nsg and LB is visible

Case 2 NOK: create a network security group, attach it to a compute, and check the box show connections, no link is visible between the compute instance and the network security group

**Comment by toxophilist** [comment]
Resolved in 0.47.0
