### ISSUE TITLE
Compute instance properties always shows 3 AD

### ISSUE THREAD

**Issue by tassamartz** [oracle/oci-designer-toolkit#562]
in Okit select Jeddah region, select a compute VM, in properties we always see 3 ADs.  Not sure if this is a bug or on purpose.

**Comment by toxophilist** [comment]
This is by design.

Because a design can be created without knowing the ultimate deployment region OKIT allows specification of AD 1-3 at build time if the deployment region is single AD it will convert them to AD 1
