### ISSUE TITLE
Data Science Services artefacts inclusion

### ISSUE THREAD

**Issue by borkur** [oracle/oci-designer-toolkit#567]
It would be great to get the Data Science Services artefcats  included in the toolkit

- Projects
- Notebook sessions
- Models & Model Deployments
- Vaults, keys, and secrets.

**Comment by toxophilist** [comment]
@borkur Vaults & Keys are already included but I'll look at the others.

**Comment by borkur** [comment]
Thanks! it would be a very useful feature for us

**Comment by toxophilist** [comment]
Data Science Project / Notebooks will be in 0.47.0
