### ISSUE TITLE
Generated BOM is incorrect

### ISSUE THREAD

**Issue by andytael** [oracle/oci-designer-toolkit#579]
When introspecting my tenancy where I run an OKE cluster (3 nodes 1 OCPU, 16GB of RAM), an ATP instance and a number of block volumes the BOM generated is incorrect.  This is the BOM generated, I've attached the okit.json file.

Part | Quantity | Description | List Price | Units | Utilisation | Monthly Cost
-- | -- | -- | -- | -- | -- | --
B89040 | 1 | Oracle Autonomous Data Warehouse (OCPU Per Hour) | $1.34410 | 1 | 744 | $1,000.01
B89041 | 1 | Oracle Autonomous Data Warehouse - Exadata Storage (Terabyte Storage Capacity Per Month) | $118.40000 | 1 | 1 | $118.40
B91627 | 2 | Object Storage - Requests (10,000 Requests per Month (first 50,000 free)) | 0-5: $0.00000 5-999999999: $0.00340 | 2 | 2 | $0.00
B91628 | 2 | Object Storage - Storage (Gigabyte Storage Capacity Per Month) | 0-10: $0.00000 10-999999999: $0.02550 | 2 | 2 | $0.00
B91961 | 11 | Storage - Block Volume - Storage (Gigabyte Storage Capacity Per Month) | $0.02550 | 850 | 11 | $21.67
B91962 | 11 | Storage - Block Volume - Performance Units (Performance Units Per Gigabyte Per Month) | $0.00170 | 850 | 110 | $14.45
B93030 | 1 | Load Balancer Base (Load Balancer) | 0-744: $0.00000 744-999999999: $0.01130 | 1 | 744 | $8.41
B93031 | 1 | Load Balancer Bandwidth (Mbps Per Hour) | 0-7440: $0.00000 7440-999999999: $0.00010 | 100 | 744 | $6.70
B93113 | 1 | Compute - Standard - E4 - OCPU (OCPU Per Hour) | $0.02500 | 1 | 744 | $18.60
B93114 | 1 | Compute - Standard - E4  - Memory (Gigabyte Per Hour) | $0.00150 | 1 | 744 | $1.12

[okit.json.zip](https://github.com/oracle/oci-designer-toolkit/files/11179802/okit.json.zip)

**Comment by toxophilist** [comment]
Added OKE Pricing / BoM to 0.49.0 release
