### ISSUE TITLE
IPSec Option missing 

### ISSUE THREAD

**Issue by tariqalimkhan** [oracle/oci-designer-toolkit#58]
I see that the pallete has the option for FastConnect but I don't see IPSec VPN option, though i see the list properties of DRG showing that.

**Comment by toxophilist** [comment]
@tariqalimkhan which version are you using because the fast connect has been removed from the palette given it was there by mistake.

**Comment by tariqalimkhan** [comment]
Thanks for your reply. I am using 0.8. 
![image](https://user-images.githubusercontent.com/48773650/89291209-f9612180-d60e-11ea-9850-a9c59941aaf5.png)

**Comment by tariqalimkhan** [comment]
In fact this is the palette I have
![image](https://user-images.githubusercontent.com/48773650/89308119-be6ae800-d626-11ea-8dbd-95069a7e6f7e.png)

**Comment by toxophilist** [comment]
@tariqalimkhan Yes we currently have some miss match and the IPSec code was pulled from an earlier release because it was in complete. The intension was that DRG / FastConnect/IPSec all be released at the same time but this did not happen. We are looking at getting this resolved as soon as we can.

**Comment by toxophilist** [comment]
Added to the 0.12.0 release
