### ISSUE TITLE
Unable to Query OCI the status show retrieving.....

### ISSUE THREAD

**Issue by pinyoud** [oracle/oci-designer-toolkit#606]
Hi,
   I think OCI CLI configuration file works fine as below
![image](https://github.com/oracle/oci-designer-toolkit/assets/118237663/da059bd8-792e-41d6-8639-cd8346d4fdfc)

but for OKIT, I run docker with cmd 
![image](https://github.com/oracle/oci-designer-toolkit/assets/118237663/ae76fa7f-2f47-4056-a1df-4e8faa7334f7)
 
and then try to query OCI it does not work. it shows retrieving forever.
![image](https://github.com/oracle/oci-designer-toolkit/assets/118237663/34a1d2cb-e121-4b45-a2da-2814dfe364d0)

**Comment by toxophilist** [comment]
@pinyoud can you try the 0.54.3 release

**Comment by pinyoud** [comment]
the issue is closed. I tried to build v0.54.4 in OLE7.9(the issue occurs in OLE8 env, don't know why), and now it works fine. Thanks for your response.
![image](https://github.com/oracle/oci-designer-toolkit/assets/118237663/8a888951-e409-4ede-ab66-69e9a58ef7b9)
