### ISSUE TITLE
Issue with DRG attachment code in OKIT v0.8.0

### ISSUE THREAD

**Issue by sunil-warrier** [oracle/oci-designer-toolkit#61]
When creating a DRG, and then exporting the diagram into ansible, the main.yml creates the below and it errors out when parsing the main.yml under "Create DRG attachment".  it looks like the objectionable lines are 
        drg_id = "{{ Okit_Drg001_ocid }}"
        vcn_id = "{{ Okit_Vcn001_id }}"

I believe the "=" needs to be replaced by ":"? 

here is a part of the main.yml

# ------ Create Dynamic Routing Gateway
    - name: Create Dynamic Routing Gateway okit-drg001
      oci_drg:
        region: "{{ region }}"
        state: "present"
        # Required
        compartment_id: "{{ Okit_Comp002_id }}"
        # Optional
        display_name: "{{ Okit_Drg001_display_name }}"
      register: Okit_Drg001

    - set_fact:
        Okit_Drg001_id: "{{ Okit_Drg001.dynamic_routing_gateway.id }}"
        Okit_Drg001_ocid: "{{ Okit_Drg001.dynamic_routing_gateway.id }}"

# ------ Create DRG Attachment
    - name: Create DRG Attachment okit-drg001
      oci_drg_attachment:
        state: "present"
        drg_id = "{{ Okit_Drg001_ocid }}"
        vcn_id = "{{ Okit_Vcn001_id }}"
        # Optional
        display_name: "{{ Okit_Drg001_display_name }}"

    - name: Get all the services in a region
      oci_service_facts:
        region: "{{ region }}"
        #name: "{{ Okit_Sg001_service_name }}"
      register: Okit_Sg001Service

**Comment by toxophilist** [comment]
Fixed in 0.9.0
