### ISSUE TITLE
Generated terraform codes create VCN resources (eg: Route Table) under Deployment Compartment

### ISSUE THREAD

**Issue by jahangir2526** [oracle/oci-designer-toolkit#618]
VCN resources (Security List, Route Table, DHCP Option) those are not VCN default being created in Deployment Compartment. This should be created in  VCN compartment. please find the attached screenshot.

<img width="818" alt="Screenshot 2023-09-30 at 3 07 27 AM" src="https://github.com/oracle/oci-designer-toolkit/assets/33924742/fd0c4692-86f8-4ebf-955d-2e84f203dd98">

**Comment by toxophilist** [comment]
@jahangir2526 Which compartment is the VCN created it. Can you paste your VCN terraform

**Comment by toxophilist** [comment]
Added to OCD [Release](https://github.com/oracle/oci-designer-toolkit/releases)
