### ISSUE TITLE
No Canvas/Load Menu option

### ISSUE THREAD

**Issue by camsaway** [oracle/oci-designer-toolkit#629]
Within the Canvas Menu there is no Load option as specified in the usage documentation. Without this, how do I load designs that I have saved to github?

![image](https://github.com/oracle/oci-designer-toolkit/assets/56301193/71c49179-68c8-42d9-8548-8d8a8d51ad79)

**Comment by toxophilist** [comment]
@camsaway Doc error this was renamed import->OKIT Json

Also if you connect okit to your git report you can pick the file directly from the git View selected from the icon on the left edge

**Comment by camsaway** [comment]
this works perfectly. Thank you.

**Comment by toxophilist** [comment]
@camsaway The Load was changed to Import->OKIT Json. I'll update the docs
