### ISSUE TITLE
.exe was flagged by Windows Security

### ISSUE THREAD

**Issue by rheadrickTSC** [oracle/oci-designer-toolkit#630]
The exe file was flagged by Windows Security as malicious.

https://github.com/oracle/oci-designer-toolkit/releases/download/v0.1.0-alpha.ocd.nightly/ocd-0.1.0-alpha.exe

**Comment by toxophilist** [comment]
@rheadrickTSC This is because the alpha attachments have not had the appropriate Mac/Windows developer Certificates attached. On the Mac I know I'm allowed to override this type of warning and I believe you can do the same on Windows.

**Comment by toxophilist** [comment]
@rheadrickTSC Did you manage to override the warning. If not if you clone the repository the node build scripts can be run directory to get a local build.
