### ISSUE TITLE
Issue with ansible code in main.yml when creating tcp options

### ISSUE THREAD

**Issue by sunil-warrier** [oracle/oci-designer-toolkit#65]
OKIt v 0.8.0
When: Create a diagram with security list having ingress or egress rule with tcp options. After exporting this into ansible, the main.yml shows max and min variables without quotes.  This is causing issues with parsing yaml. Once i put them in quotes the issue gets resolved.
For example:
+--------------------------------------+
              tcp_options:
                destination_port_range:
                    min: {{ Okit_Sl002_ingress_rule_01_tcp_dst_min }}
                    max: {{ Okit_Sl002_ingress_rule_01_tcp_dst_max }}
              # Required
            - protocol: "{{ Okit_Sl002_ingress_rule_02_protocol }}"
              source: "{{ Okit_Sl002_ingress_rule_02_source }}"
              # Optional
              source_type: "{{ Okit_Sl002_ingress_rule_02_source_type }}"
              tcp_options:
                destination_port_range:
                    min: {{ Okit_Sl002_ingress_rule_02_tcp_dst_min }}
                    max: {{ Okit_Sl002_ingress_rule_02_tcp_dst_max }}
        # Optional
+--------------------------------------+

**Comment by toxophilist** [comment]
Fixed in 0.9.0 odd though given they are integer values
