### ISSUE TITLE
EHN REQ: Populate terraform.tfvars with active profile

### ISSUE THREAD

**Issue by samktan** [oracle/oci-designer-toolkit#650]
Currently (OKIT 0.60 and 0.61) generate a blank terraform.tfvars file and the user is expected to populate it post export. It would be helpful to pre-populate the file with the contents of the currently active profile that is selected in OKIT, even as a starting point.

**Comment by samktan** [comment]
OK understood. It's just inconvenient to have to store connection information in .oci/config *and* in connection.tfvars and to keep them in sync. I guess some shell scripting is called for.

**Comment by toxophilist** [comment]
@samktan The alternative is to export to Resource Manager which would use the connection information.
