### ISSUE TITLE
Unable to Connect to Localhost

### ISSUE THREAD

**Issue by Rinjhin** [oracle/oci-designer-toolkit#7]
$ ./start-okit-server.sh
OCI_CONFIG_DIR has not been set using /c/Users/RBANERJE/.oci
OKIT_OUTPUT_DIR has not been set using /c/Users/RBANERJE/oci-designer-toolkit/output

==========================================================================
=====  Runtime : gunicorn                                            =====
=====  Version : 0.5.0                                               =====
=====  Image   : okit/0.5.0/webserver                                =====
==========================================================================

the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS               NAMES
c43339fbaa76        docker101tutorial   "nginx -g 'daemon of…"   52 minutes ago      Exited (0) 11 minutes ago
                       docker-tutorial

RBANERJE-LAP+RBANERJE@RBANERJE-LAP MINGW64 ~/oci-designer-toolkit/docker ((v0.5.0))
$ 
However, when navigated to http://localhost/okit/designer, I am getting the error 'Unable to connect'.  Is there any step I am missing?

**Comment by toxophilist** [comment]
What OS are you running this on I've not seen the TTY issue before.

**Comment by Rinjhin** [comment]
I am running this on a gitbash shell on a Windows machine.

**Comment by Rinjhin** [comment]
When I built the image, I got this message:
Successfully tagged okit/0.5.0/webserver:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files
 and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double 
check and reset permissions for sensitive files and directories.
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
okit/0.5.0/webserver   latest              fcc1f684621e        8 seconds ago       234MB
docker101tutorial      latest              0976f3071b91        18 hours ago        24.8MB
oraclelinux            7-slim              3f15c01b91bb        9 days ago          120MB
python                 alpine              6c32e2504283        2 weeks ago         107MB
node                   12-alpine           7a48db49edbf        2 weeks ago         88.7MB
nginx                  alpine              89ec9da68213        2 weeks ago         19.9MB
*******************************************************************
**                                                               **
**  Image Build Complete                                         **
**  okit/0.5.0/webserver
**                                                               **
*******************************************************************
I downloaded docker for Windows yesterday, but I am building the okit and trying to start it up on a gitbash shell on Windows.

**Comment by toxophilist** [comment]
I'm currently looking at changing the instruction for building the docker image so it does not rely on the shell scripts. It will include an entrypoint to automatically start the server.

**Comment by Rinjhin** [comment]
Is there any way to fix my install and bring up the local host?

**Comment by toxophilist** [comment]
Until I push the changes I’m working on you could try the Vagrant installation. It may appear to error the first run but it’s just the web server being slow to start.

**Comment by toxophilist** [comment]
@Rinjhin I've been doing some work on the docker file and the repo has been updated to contain the slightly modified file and I have changed the instruction to show the Docker commands to be execute rather than a bash script. If you try the docker commands you should be able to run this on Windows directly jsut change the `pwd` to the clone location.

**Comment by Rinjhin** [comment]
I followed the latest instructions, got the new clone, built and started the image again:
RBANERJE-LAP+RBANERJE@RBANERJE-LAP MINGW64 ~/oci-designer-toolkit ((v0.5.1))
$ docker run -d --rm -p 80:80 \
>            --name okit \
>            --hostname okit \
>            -v ~/.oci:/root/.oci:Z \
>            -v `pwd`/okitweb:/okit/okitweb:Z \
>            -v `pwd`/visualiser:/okit/visualiser:Z \
>            -v `pwd`/log:/okit/log:Z \
>            okit
b28e3c27c1bb0e8573fa80e2fbbef0b9afc2bc976fd34e332025248039b448e3
However, still connecting to local host fails when I do 'http://localhost/okit/designer' on the browser

**Comment by toxophilist** [comment]
Can you execute 
```bash
docker container ls --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}" -a
```

It should show something like

```bash
CONTAINER ID        NAMES               PORTS
c1db3b51dfaf        okit                0.0.0.0:80->80/tcp, 443/tcp
```

Which indicates that port 80 is exposed to the host system.

Also if you replace the -d with -it in the docker run command you will see what port it gunicorn is listening on.

The new docker command does assume you have rebuild your docker container.

**Comment by Rinjhin** [comment]
Yes, I have followed the instructions and re-built the container with 'docker build ...' command.  As I run the command: 'docker container ls --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}" -a', I see:
CONTAINER ID        NAMES               PORTS
c43339fbaa76        docker-tutorial
I don't see okit there.  If I run docker images, I see okit:
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
okit                   latest              1c2c2113963c        8 minutes ago       234MB
okit/0.5.0/webserver   latest              fcc1f684621e        4 days ago          234MB
docker101tutorial      latest              0976f3071b91        4 days ago          24.8MB
oraclelinux            7-slim              3f15c01b91bb        13 days ago         120MB
python                 alpine              6c32e2504283        2 weeks ago         107MB
node                   12-alpine           7a48db49edbf        2 weeks ago         88.7MB
nginx                  alpine              89ec9da68213        3 weeks ago         19.9MB
Am I missing something here?

**Comment by toxophilist** [comment]
@Rinjhin can you try running the command replacing the -d with -it

**Comment by Rinjhin** [comment]
I deleted everything, got the clone again and ran the following:
$ docker build --tag okit --file ./containers/docker/Dockerfile --force-rm ./containers/docker/
Sending build context to Docker daemon  8.704kB
Step 1/9 : FROM oraclelinux:7-slim
 ---> 3f15c01b91bb
Step 2/9 : LABEL "provider"="Oracle"       "issues"="https://github.com/oracle/oci-designer-toolkit/issues"       "version"="0.5.1"       "description"="OKIT Web Server Container."       "copyright"="Copyright (c) 2020, Oracle and/or its affiliates."
 ---> Using cache
 ---> b3694664f268
Step 3/9 : SHELL ["/bin/bash", "-c"]
 ---> Using cache
 ---> 46e9dcd99cd4
Step 4/9 : ENV PYTHONIOENCODING=utf8     PYTHONPATH=":/okit/visualiser:/okit/okitweb:/okit"     FLASK_APP=okitweb     FLASK_DEBUG=1     LANG=en_GB.UTF-8     LANGUAGE=en_GB:en     LC_ALL=en_GB.UTF-8     PATH=/root/bin:${PATH}
 ---> Using cache
 ---> 8cc8e20ca89b
Step 5/9 : EXPOSE 80
 ---> Using cache
 ---> 68024f8b26df
Step 6/9 : EXPOSE 443
 ---> Using cache
 ---> 368c1fa50254
Step 7/9 : RUN yum install -y     oracle-softwarecollection-release-el7  && yum update -y  && yum install -y         python36         python3-pip  && rm -rf /var/cache/yum  && python3 -m pip install --upgrade pip==20.0.2  && pip3 install --no-cache-dir         click==7.0         flask==1.1.1         gunicorn==20.0.4         itsdangerous==1.1.0         jinja2==2.10.3         markupsafe==1.1.1         oci==2.6.0         pyyaml==5.2         werkzeug==0.16.0         cryptography==2.8  && mkdir -p /okit/{config,log,visualiser,okitweb,workspace}
 ---> Using cache
 ---> 844a248c7ec2
Step 8/9 : ENTRYPOINT ["gunicorn"]
 ---> Using cache
 ---> 25505dfa2399
Step 9/9 : CMD ["--workers=2", "--limit-request-line", "0", "--bind=0.0.0.0:80", "okitweb.wsgi:app"]
 ---> Using cache
 ---> 1c2c2113963c
Successfully built 1c2c2113963c
Successfully tagged okit:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

RBANERJE-LAP+RBANERJE@RBANERJE-LAP MINGW64 ~/oci-designer-toolkit ((v0.5.1))
$ pwd
/c/Users/RBANERJE/oci-designer-toolkit

RBANERJE-LAP+RBANERJE@RBANERJE-LAP MINGW64 ~/oci-designer-toolkit ((v0.5.1))
$ ls
CHANGELOG.md     documentation/  README.md                 visualiser/
containers/      LICENSE.txt     sonar-project.properties
CONTRIBUTING.md  okitweb/        THIRD_PARTY_LICENSES.txt

RBANERJE-LAP+RBANERJE@RBANERJE-LAP MINGW64 ~/oci-designer-toolkit ((v0.5.1))
$ ls -ltr
total 73
-rw-r--r-- 1 RBANERJE-LAP+RBANERJE 197121  4555 May 19 10:56 CHANGELOG.md
-rw-r--r-- 1 RBANERJE-LAP+RBANERJE 197121  2114 May 19 10:56 CONTRIBUTING.md
-rw-r--r-- 1 RBANERJE-LAP+RBANERJE 197121  2626 May 19 10:56 README.md
-rw-r--r-- 1 RBANERJE-LAP+RBANERJE 197121  1880 May 19 10:56 LICENSE.txt
-rw-r--r-- 1 RBANERJE-LAP+RBANERJE 197121 40774 May 19 10:56 THIRD_PARTY_LICENSES.txt
drwxr-xr-x 1 RBANERJE-LAP+RBANERJE 197121     0 May 19 10:56 containers/
drwxr-xr-x 1 RBANERJE-LAP+RBANERJE 197121     0 May 19 10:56 documentation/
drwxr-xr-x 1 RBANERJE-LAP+RBANERJE 197121     0 May 19 10:56 okitweb/
-rw-r--r-- 1 RBANERJE-LAP+RBANERJE 197121   228 May 19 10:56 sonar-project.properties
drwxr-xr-x 1 RBANERJE-LAP+RBANERJE 197121     0 May 19 10:56 visualiser/

RBANERJE-LAP+RBANERJE@RBANERJE-LAP MINGW64 ~/oci-designer-toolkit ((v0.5.1))
$ docker run -it --rm -p 80:80 \
>            --name okit \
>            --hostname okit \
>            -v ~/.oci:/root/.oci:Z \
>            -v `pwd`/okitweb:/okit/okitweb:Z \
>            -v `pwd`/visualiser:/okit/visualiser:Z \
>            -v `pwd`/log:/okit/log:Z \
>            okit
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

RBANERJE-LAP+RBANERJE@RBANERJE-LAP MINGW64 ~/oci-designer-toolkit ((v0.5.1))
Please help

**Comment by toxophilist** [comment]
@Rinjhin 

The pwd will not work on windows as far as I know can you try.

#### Start Docker Image
- OKIT_ROOT_DIR  : Absolute directory name for the extracted / cloned OKIT repository
- OCI_CONFIG_DIR : Directory containing the OCI config file. Details can be found in [OCI Designer Toolkit Installation Guide](documentation/Installation.md#oci-config-file).

```bash
cd oci-designer-toolkit
docker run -d --rm -p 80:80 \
           --name okit \
           --hostname okit \
           -v <OCI_CONFIG_DIR>:/root/.oci \
           -v <OKIT_ROOT_DIR>/okitweb:/okit/okitweb \
           -v <OKIT_ROOT_DIR>/visualiser:/okit/visualiser \
           -v <OKIT_ROOT_DIR>/log:/okit/log \
           okit
```

Version 0.7.0 will ship with some PowerShell scripts to build & start docker in the containers/scripts directory

**Comment by rafdanzi** [comment]
Hi, when would be this 0.7 Version delivered?

**Comment by toxophilist** [comment]
24th June

**Comment by rafdanzi** [comment]
Thanks!
