### ISSUE TITLE
gateway creation issues

### ISSUE THREAD

**Issue by dongwookim1004** [oracle/oci-designer-toolkit#71]
I am using okit 0.9.1 version

After creating 2 vcns, add internet gateway, nat gateway and service gateway, but only 1 gateway is created.

For example
If you create an internet gateway in vcn1, you cannot create an internet gateway in vcn2.

**Comment by toxophilist** [comment]
@dongwookim1004 I know what the issues is the fix will be in the next release but I'll look at a point release next week.

**Comment by toxophilist** [comment]
Fixed in 0.9.2 release
