### ISSUE TITLE
Vagrant image failes to install V0.9.2

### ISSUE THREAD

**Issue by soeremk** [oracle/oci-designer-toolkit#75]
Hi when I try to install the latest 0.9.2 version it gives an error 
This is snipped from the install:

    okit-vagrant: ============== Running privileged commands ==============
==> okit-vagrant: Running provisioner: shell...
    okit-vagrant: Running: inline script
==> okit-vagrant: Running provisioner: file...
    okit-vagrant: ../../okitweb => /okit/okitweb
==> okit-vagrant: Running provisioner: file...
    okit-vagrant: ../../visualiser => /okit/visualiser
==> okit-vagrant: Running provisioner: file...
    okit-vagrant: ../oci => /okit/config
==> okit-vagrant: Running provisioner: shell...
    okit-vagrant: Running: inline script
==> okit-vagrant: Running provisioner: shell...
    okit-vagrant: Running: inline script
==> okit-vagrant: Running provisioner: shell...
    okit-vagrant: Running: inline script
    okit-vagrant: chmod:
    okit-vagrant: cannot access ‘/root/.oci/*.pem’
    okit-vagrant: : No such file or directory

It does not looks like something I address 

Regards
Mads

**Comment by toxophilist** [comment]
Before you built the Vagrant image did you copy you oci config file / pem file to the oci-designer-toolkit/containers/oci directory. The Vagrant build will copy them from that directory into the Vagrant image.

**Comment by toxophilist** [comment]
@soeremk Can you try this with the latest release but prior to building the Vagrant image you will need to make sure that the config exists in containers/oci and your pem key has been copied to the containers/oci directory. The contents of this directory will be copied to the image.
