### ISSUE TITLE
Resource Manager fails

### ISSUE THREAD

**Issue by fatih-keles** [oracle/oci-designer-toolkit#9]
Resource manager menu option fails with the following log.

**Comment by fatih-keles** [comment]
[log.txt](https://github.com/oracle/oci-designer-toolkit/files/4628236/log.txt)

**Comment by fatih-keles** [comment]
[okit.json.txt](https://github.com/oracle/oci-designer-toolkit/files/4628250/okit.json.txt)

**Comment by fatih-keles** [comment]
![image](https://user-images.githubusercontent.com/34371716/81934047-f699f600-95f6-11ea-86df-96cebcda2ee5.png)

**Comment by toxophilist** [comment]
If you change the name of the top level compartment to one that exists in your account the export will work. At the moment you still have the okit-comp001 default at the top level which is not a valid compartment name for your account.

**Comment by toxophilist** [comment]
Hi Sorry just spotted the exact issue which is that RM upload via the python api only allows 100 variable for a stack and the generated terraform.tfvars contains more than 100. This is an oddity associated with RM.

**Comment by toxophilist** [comment]
100 variable restriction issues will be fixed in v0.6.0
