### ISSUE TITLE
Loadbalancer - Backend Instances	multi target issue

### ISSUE THREAD

**Issue by dongwookim1004** [oracle/oci-designer-toolkit#94]
I am using okit 0.10.2 version

Cannot target multiple Backend Instances in a load-balancer.

**Comment by toxophilist** [comment]
@dongwookim1004 can you expand on your issue.

**Comment by dongwookim1004** [comment]
Load Balancer Properties -> Backend Instances -> cannot select multiple check-boxes. (only one check-box)

> @dongwookim1004 can you expand on your issue.

**Comment by toxophilist** [comment]
The backends is a multi select list not check boxes so use shift/Ctrl for windows or Shift/Command on Mac to select multiple.

**Comment by dongwookim1004** [comment]
OK~
Thank you~
