### ISSUE TITLE
Unable to upgrade to latest version (v0.10.2)

### ISSUE THREAD

**Issue by rastangineer** [oracle/oci-designer-toolkit#96]
Hi team,

I'm trying to use the latest version of OKIT, but when I start the docker image and open the UI I just see this on the UI:

![image](https://user-images.githubusercontent.com/2855696/92531320-abce6a80-f1f3-11ea-87e4-3cb7ae8f4db2.png)

## Versions

OKIT Version: `v0.10.2` (although OKIT UI shows `v0.9.2`)
Browser: Chrome 85.0.4183.83

## Steps to reproduce:

1. Clone repo
2. Execute `docker-compose up`
3. Open OKIT UI
4. UI shows an incorrect version (`v0.9.2`) on the left bottom of the page

Note: I have tried both branches `v0.10.2`  and `master`. and start the container again, but same behaviour.

What am I doing wrong?

Thanks for your help

**Comment by toxophilist** [comment]
The files will be copied to the image during build. Can you try running docker-compose build to force the image to be rebuilt.

**Comment by rastangineer** [comment]
Thanks @toxophilist,

After building the image, I can see the correct version on the UI.
