### ISSUE TITLE
Error trying to deploy HA Web Application architecture template

### ISSUE THREAD

**Issue by rastangineer** [oracle/oci-designer-toolkit#98]
Hi,

I'm trying to deploy HA Web Aplication Reference Architecture template but I'm having the following error :

![image](https://user-images.githubusercontent.com/2855696/92647682-e7c60600-f2ad-11ea-9345-341c9de6129f.png)

## Versions

OKIT Version: `v0.10.2`
Browser: Chrome 85.0.4183.83

## Steps to reproduce

1. Open HA Web Application template (`Menu-> Templates-> Reference Architecture -> HA Web Application`)
2. Specify public keys for DB System, webhosts (1 and 2) and bastion instances.
3. Export via Resource Manager (`Menu-> Export-> Resource Manager`)
4. Leave options default (create and plan), then click `Create Stack`
5. See the popup with the error message:
```
Export to Resource Manager Failed (INTERNAL SERVER ERROR)
```
6. On the log I can see this error:
```
okit    | INFO: Processing Route Table Information Okit_Rt003
okit    | INFO: Processing Subnet Information Ha_Web_Public_Sn
okit    | INFO: Processing Subnet Information Ha_Web_Private_Sn
okit    | INFO: Processing Subnet Information Ha_Web_Db_Sn
okit    | INFO: Processing Database System Information Hawebdb
okit    | ERROR: '>' not supported between instances of 'str' and 'int'
okit    | Traceback (most recent call last):
okit    |   File "/okit/okitweb/okitOci.py", line 110, in ociResourceManger
okit    |     generator.generate()
okit    |   File "/okit/visualiser/generators/okitGenerator.py", line 194, in generate
okit    |     self.renderDatabaseSystem(database_system)
okit    |   File "/okit/visualiser/generators/okitGenerator.py", line 371, in renderDatabaseSystem
okit    |     if database_system["cpu_core_count"] > 0:
okit    | TypeError: '>' not supported between instances of 'str' and 'int'
```

**Note**: On `v0.9.2` I was able to deploy without any issues.

Thanks for your help

**Comment by toxophilist** [comment]
Will be fixed in the 0.11.0 release
